export const allWords=[{engText : 'jl',punjabiText: 'ਜਲ',meaning:'Water',level:1},
{engText : 'kl',punjabiText: 'ਕਲ',meaning:'Tomorrow',level:1},
{engText : 'Ql',punjabiText: 'ਥਲ',meaning:'Land',level:1},
{engText : 'mn',punjabiText: 'ਮਨ',meaning:'Mind',level:1},
{engText : 'sc',punjabiText: 'ਸਚ',meaning:'Truth',level:1},
{engText : 'nr',punjabiText: 'ਨਰ',meaning:'Human',level:1},
{engText : 'fr',punjabiText: 'ਡਰ',meaning:'Fear',level:1},
{engText : 'ds',punjabiText: 'ਦਸ',meaning:'10 or Ten',level:1},
{engText : 'qn',punjabiText: 'ਤਨ',meaning:'Body',level:1},
{engText : 'krm',punjabiText: 'ਕਰਮ',meaning:'Deed',level:1},
{engText : 'Drm',punjabiText: 'ਧਰਮ',meaning:'Religion or Righteousness',level:1},
{engText : 'klm',punjabiText: 'ਕਲਮ',meaning:'Pen',level:1},
{engText : 'grm',punjabiText: 'ਗਰਮ',meaning:'Hot',level:1},
{engText : 'kml',punjabiText: 'ਕਮਲ',meaning:'Lotus',level:1},
{engText : 'sVk',punjabiText: 'ਸੜਕ',meaning:'Road',level:1},
{engText : 'sbr',punjabiText: 'ਸਬਰ',meaning:'Patience',level:1},
{engText : 'kr',punjabiText: 'ਕਰ',meaning:'Do',level:2},
{engText : 'cl',punjabiText: 'ਚਲ',meaning:'Walk',level:2},
{engText : 'gl',punjabiText: 'ਗਲ',meaning:'Talk',level:2},
{engText : 'ds',punjabiText: 'ਦਸ',meaning:'Tell',level:2},
{engText : 'Pl',punjabiText: 'ਫਲ',meaning:'Fruit',level:2},
{engText : 'Cq',punjabiText: 'ਛਤ',meaning:'Roof',level:2},
{engText : 'hl',punjabiText: 'ਹਲ',meaning:'Plough',level:2},
{engText : 'Akl',punjabiText: 'ਅਕਲ',meaning:'Wisdom',level:2},
{engText : 'Brm',punjabiText: 'ਭਰਮ',meaning:'Illusion',level:2},
{engText : 'Skl',punjabiText: 'ਸ਼ਕਲ',meaning:'Face',level:2},
{engText : 'jgq',punjabiText: 'ਜਗਤ',meaning:'World',level:2},
{engText : 'sPr',punjabiText: 'ਸਫਰ',meaning:'Journey',level:2},
{engText : 'drKq',punjabiText: 'ਦਰਖਤ',meaning:'Tree',level:2},
{engText : 'ksrq',punjabiText: 'ਕਸਰਤ',meaning:'Exercise',level:2},
{engText : 'grdn',punjabiText: 'ਗਰਦਨ',meaning:'Neck',level:2},
{engText : 'Srbq',punjabiText: 'ਸ਼ਰਬਤ',meaning:'Syrup, Juice',level:2},
{engText : 'drSn',punjabiText: 'ਦਰਸ਼ਨ',meaning:'Glimpse, Sight',level:2},
{engText : 'mwqw',punjabiText: 'ਮਾਤਾ',meaning:'Mother',level:3},
{engText : 'rwg',punjabiText: 'ਰਾਗ',meaning:'Melody (Raag)',level:3},
{engText : 'kwl',punjabiText: 'ਕਾਲ',meaning:'Time',level:3},
{engText : 'jwl',punjabiText: 'ਜਾਲ',meaning:'Trap',level:3},
{engText : 'nwm',punjabiText: 'ਨਾਮ',meaning:'Name',level:3},
{engText : 'rwj',punjabiText: 'ਰਾਜ',meaning:'Kingdom',level:3},
{engText : 'dws',punjabiText: 'ਦਾਸ',meaning:'Disciple',level:3},
{engText : 'swD',punjabiText: 'ਸਾਧ',meaning:'Saint',level:3},
{engText : 'bwz',punjabiText: 'ਬਾਜ਼',meaning:'Eagle',level:3},
{engText : 'hrw',punjabiText: 'ਹਰਾ',meaning:'Green',level:3},
{engText : 'kVw',punjabiText: 'ਕੜਾ',meaning:'Iron bangle worn by Sikhs, which represents the creator is infinite/limitless and also stops bad deeds.',level:3},
{engText : 'kmwl',punjabiText: 'ਕਮਾਲ',meaning:'Wonderful',level:3},
{engText : 'Akwl',punjabiText: 'ਅਕਾਲ',meaning:'Timeless (from "ਅਕਾਲ ਪੁਰਖ" Almighty God)',level:3},
{engText : 'kwrj',punjabiText: 'ਕਾਰਜ',meaning:'Work',level:3},
{engText : 'mwrg',punjabiText: 'ਮਾਰਗ',meaning:'Path',level:3},
{engText : 'kpVw',punjabiText: 'ਕਪੜਾ',meaning:'Cloth',level:3},
{engText : 'bwjwr',punjabiText: 'ਬਾਜਾਰ',meaning:'Market',level:3},
{engText : 'kwgz',punjabiText: 'ਕਾਗਜ਼',meaning:'Paper',level:3},
{engText : 'Awsrw',punjabiText: 'ਆਸਰਾ',meaning:'Support',level:3},
{engText : 'dsqwr',punjabiText: 'ਦਸਤਾਰ',meaning:'Turban',level:3},
{engText : 'ilK',punjabiText: 'ਲਿਖ',meaning:'Write',level:4},
{engText : 'iPr',punjabiText: 'ਫਿਰ',meaning:'Again',level:4},
{engText : 'iQr',punjabiText: 'ਥਿਰ',meaning:'Stable',level:4},
{engText : 'ipqw',punjabiText: 'ਪਿਤਾ',meaning:'Father',level:4},
{engText : 'ikrpwn',punjabiText: 'ਕਿਰਪਾਨ',meaning:'Sikh symbol of power and freedom of spirit, and a reminder to fight injustice and oppression.',level:4},
{engText : 'ikqwb',punjabiText: 'ਕਿਤਾਬ',meaning:'Book',level:4},
{engText : 'ikrq',punjabiText: 'ਕਿਰਤ',meaning:'Work',level:4},
{engText : 'mihr',punjabiText: 'ਮਹਿਰ',meaning:'Grace',level:4},
{engText : 'dieAw',punjabiText: 'ਦਇਆ',meaning:'Mercy, Compassion',level:4},
{engText : 'inrml',punjabiText: 'ਨਿਰਮਲ',meaning:'Pure',level:4},
{engText : 'kCihrw',punjabiText: 'ਕਛਹਿਰਾ',meaning:'Cotton shorts worn by Sikhs as a symbol of pure and righteous character.',level:4},
{engText : 'srIr',punjabiText: 'ਸਰੀਰ',meaning:'Body',level:4},
{engText : 'pwxI',punjabiText: 'ਪਾਣੀ',meaning:'Water',level:4},
{engText : 'kmweI',punjabiText: 'ਕਮਾਈ',meaning:'Earning',level:4},
{engText : 'SkqI',punjabiText: 'ਸ਼ਕਤੀ',meaning:'Power',level:4},
{engText : 'ibjlI',punjabiText: 'ਬਿਜਲੀ',meaning:'Electricity',level:4},
{engText : 'BgqI',punjabiText: 'ਭਗਤੀ',meaning:'Worship',level:4},
{engText : 'kIrqn',punjabiText: 'ਕੀਰਤਨ',meaning:'Keertan, the melodious way of singing Gurbani (the praises of the Almighty God)',level:4},
{engText : 'mskIn',punjabiText: 'ਮਸਕੀਨ',meaning:'Humble, meek',level:4},
{engText : 'pgVI',punjabiText: 'ਪਗੜੀ',meaning:'Turban',level:4},
{engText : 'KuS',punjabiText: 'ਖੁਸ਼',meaning:'Happy',level:5},
{engText : 'duD',punjabiText: 'ਦੁਧ',meaning:'Milk',level:5},
{engText : 'cup',punjabiText: 'ਚੁਪ',meaning:'Silence',level:5},
{engText : 'rumwl',punjabiText: 'ਰੁਮਾਲ',meaning:'Handkerchief',level:5},
{engText : 'cqur',punjabiText: 'ਚਤੁਰ',meaning:'Clever, Smart',level:5},
{engText : 'hukm',punjabiText: 'ਹੁਕਮ',meaning:'The eternal order',level:5},
{engText : 'gulwb',punjabiText: 'ਗੁਲਾਬ',meaning:'Rose',level:5},
{engText : 'pusqk',punjabiText: 'ਪੁਸਤਕ',meaning:'Book',level:5},
{engText : 'nukswn',punjabiText: 'ਨੁਕਸਾਨ',meaning:'Loss',level:5},
{engText : 'gurUduAwrw',punjabiText: 'ਗੁਰੂਦੁਆਰਾ',meaning:'Gurudwara, Sikh Holy place of Worship',level:5},
{engText : 'dUr',punjabiText: 'ਦੂਰ',meaning:'Far, Away',level:5},
{engText : 'nUr',punjabiText: 'ਨੂਰ',meaning:'Glow/Light on one"s face',level:5},
{engText : 'bwpU',punjabiText: 'ਬਾਪੂ',meaning:'Father',level:5},
{engText : 'AwlU',punjabiText: 'ਆਲੂ',meaning:'Potato',level:5},
{engText : 'BwlU',punjabiText: 'ਭਾਲੂ',meaning:'Bear',level:5},
{engText : 'sUrq',punjabiText: 'ਸੂਰਤ',meaning:'Facial appearance',level:5},
{engText : 'mUrK',punjabiText: 'ਮੂਰਖ',meaning:'Fool',level:5},
{engText : 'qrbUj',punjabiText: 'ਤਰਬੂਜ',meaning:'Watermelon',level:5},
{engText : 'kbUqr',punjabiText: 'ਕਬੂਤਰ',meaning:'Pigeon',level:5},
{engText : 'zrUrq',punjabiText: 'ਜ਼ਰੂਰਤ',meaning:'Need, Neccessity',level:5},
{engText : 'kys',punjabiText: 'ਕੇਸ',meaning:'Uncut hair (the first of the 5 K’s in Sikhism) which symbolizes the adoption of a simple life and denial of pride in one’s appearance. It is believed that the long hair is a sign of a Sikh’s commitment and devotion to his/her Guru.',level:6},
{engText : 'mylw',punjabiText: 'ਮੇਲਾ',meaning:'Fair',level:6},
{engText : 'ryl',punjabiText: 'ਰੇਲ',meaning:'Train',level:6},
{engText : 'qyl',punjabiText: 'ਤੇਲ',meaning:'Oil',level:6},
{engText : 'syb',punjabiText: 'ਸੇਬ',meaning:'Apple',level:6},
{engText : 'kylw',punjabiText: 'ਕੇਲਾ',meaning:'Banana',level:6},
{engText : 'svyr',punjabiText: 'ਸਵੇਰ',meaning:'Morning',level:6},
{engText : 'hnyrw',punjabiText: 'ਹਨੇਰਾ',meaning:'Darkness',level:6},
{engText : 'prySwn',punjabiText: 'ਪਰੇਸ਼ਾਨ',meaning:'Worried',level:6},
{engText : 'prdyS',punjabiText: 'ਪਰਦੇਸ਼',meaning:'Foreign',level:6},
{engText : 'pYr',punjabiText: 'ਪੈਰ',meaning:'Foot',level:6},
{engText : 'mYl',punjabiText: 'ਮੈਲ',meaning:'Dirt, Dust',level:6},
{engText : 'BYx',punjabiText: 'ਭੈਣ',meaning:'Sister',level:6},
{engText : 'vYr',punjabiText: 'ਵੈਰ',meaning:'Enmity',level:6},
{engText : 'pYsy',punjabiText: 'ਪੈਸੇ',meaning:'Money',level:6},
{engText : 'AYnk',punjabiText: 'ਐਨਕ',meaning:'Spectacles',level:6},
{engText : 'hYrwn',punjabiText: 'ਹੈਰਾਨ',meaning:'Shocked',level:6},
{engText : 'mYdwn',punjabiText: 'ਮੈਦਾਨ',meaning:'Ground',level:6},
{engText : 'pYdl',punjabiText: 'ਪੈਦਲ',meaning:'Pedestrial, (walking) on foot',level:6},
{engText : 'inrvYr',punjabiText: 'ਨਿਰਵੈਰ',meaning:'Without Enmity',level:6},
{engText : 'mor',punjabiText: 'ਮੋਰ',meaning:'Peacock',level:7},
{engText : 'cor',punjabiText: 'ਚੋਰ',meaning:'Thief',level:7},
{engText : 'rotI',punjabiText: 'ਰੋਟੀ',meaning:'Chapati, Flat Round Bread',level:7},
{engText : 'qoqw',punjabiText: 'ਤੋਤਾ',meaning:'Parrot',level:7},
{engText : 'GoVw',punjabiText: 'ਘੋੜਾ',meaning:'Horse',level:7},
{engText : 'Sor',punjabiText: 'ਸ਼ੋਰ',meaning:'Noise',level:7},
{engText : 'Koqw',punjabiText: 'ਖੋਤਾ',meaning:'Donkey',level:7},
{engText : 'poqrw',punjabiText: 'ਪੋਤਰਾ',meaning:'Grandson',level:7},
{engText : 'poqrI',punjabiText: 'ਪੋਤਰੀ',meaning:'Granddaughter',level:7},
{engText : 'AKrot',punjabiText: 'ਅਖਰੋਟ',meaning:'Walnut',level:7},
{engText : 'sOKw',punjabiText: 'ਸੌਖਾ',meaning:'Easy',level:7},
{engText : 'AOKw',punjabiText: 'ਔਖਾ',meaning:'Tough, Difficult',level:7},
{engText : 'dOV',punjabiText: 'ਦੌੜ',meaning:'Race, Run',level:7},
{engText : 'kOx',punjabiText: 'ਕੌਣ',meaning:'Who',level:7},
{engText : '&OjI',punjabiText: 'ਫ਼ੌਜੀ',meaning:'Soldier',level:7},
{engText : 'AOrq',punjabiText: 'ਔਰਤ',meaning:'Women',level:7},
{engText : 'hQOVw',punjabiText: 'ਹਥੌੜਾ',meaning:'Hammer',level:7},
{engText : 'iKfOxw',punjabiText: 'ਖਿਡੌਣਾ',meaning:'Toy',level:7},
{engText : 'cOkIdwr',punjabiText: 'ਚੌਕੀਦਾਰ',meaning:'Watchman',level:7},
{engText : 'sOdwgr',punjabiText: 'ਸੌਦਾਗਰ',meaning:'Trader',level:7},
{engText : 'kwN',punjabiText: 'ਕਾਂ',meaning:'Crow',level:8},
{engText : 'gwN',punjabiText: 'ਗਾਂ',meaning:'Cow',level:8},
{engText : 'CwN',punjabiText: 'ਛਾਂ',meaning:'Shadow',level:8},
{engText : 'gyNd',punjabiText: 'ਗੇਂਦ',meaning:'Ball',level:8},
{engText : 'bwNdr',punjabiText: 'ਬਾਂਦਰ',meaning:'Monkey',level:8},
{engText : 'kMGw',punjabiText: 'ਕੰਘਾ',meaning:'Wooden Comb, which symbolizes cleanliness and the importance of discipline.',level:8},
{engText : 'rMg',punjabiText: 'ਰੰਗ',meaning:'Color',level:8},
{engText : 'cMn',punjabiText: 'ਚੰਨ',meaning:'Moon',level:8},
{engText : 'bsMq',punjabiText: 'ਬਸੰਤ',meaning:'Spring',level:8},
{engText : 'jMgl',punjabiText: 'ਜੰਗਲ',meaning:'Jungle',level:8},
{engText : 's`p',punjabiText: 'ਸੱਪ',meaning:'Snake',level:8},
{engText : 'A`K',punjabiText: 'ਅੱਖ',meaning:'Eye',level:8},
{engText : 'ic`TI',punjabiText: 'ਚਿੱਠੀ',meaning:'Letter',level:8},
{engText : 'ib`lI',punjabiText: 'ਬਿੱਲੀ',meaning:'Cat',level:8},
{engText : 'im`qr',punjabiText: 'ਮਿੱਤਰ',meaning:'Friend',level:8},
{engText : 'AimRq',punjabiText: 'ਅਮ੍ਰਿਤ',meaning:'Beyond Death, Holy Nectar taken by Sikh’s when they get Amritpaan (baptised)',level:8},
{engText : 'pVH',punjabiText: 'ਪੜ੍ਹ',meaning:'Read',level:8},
{engText : 'sÍYjIvnI',punjabiText: 'ਸ੍ਵੈਜੀਵਨੀ',meaning:'Auto-biography',level:8},
{engText : 'jVH',punjabiText: 'ਜੜ੍ਹ',meaning:'Root',level:8},
{engText : 'sÍr',punjabiText: 'ਸ੍ਵਰ',meaning:'Vowel',level:8},
{engText : 'Gr jw',punjabiText: 'ਘਰ ਜਾ',meaning:'Go Home',level:9},
{engText : 'jg PV',punjabiText: 'ਜਗ ਫੜ',meaning:'Hold the Jug',level:9},
{engText : 'nwm jp',punjabiText: 'ਨਾਮ ਜਪ',meaning:'Chant the name',level:9},
{engText : 'kMGw kr',punjabiText: 'ਕੰਘਾ ਕਰ',meaning:'Do Comb',level:9},
{engText : 'pgVI bMn',punjabiText: 'ਪਗੜੀ ਬੰਨ',meaning:'Tie Turban',level:9},
{engText : 'rotI Kw',punjabiText: 'ਰੋਟੀ ਖਾ',meaning:'Eat Chapati/Roti',level:9},
{engText : 'kIrqn kr',punjabiText: 'ਕੀਰਤਨ ਕਰ',meaning:'Do Keertan',level:9},
{engText : 'ic`TI pV',punjabiText: 'ਚਿੱਠੀ ਪੜ',meaning:'Read the letter',level:9},
{engText : 'klm nwl ilK',punjabiText: 'ਕਲਮ ਨਾਲ ਲਿਖ',meaning:'Write with Pen',level:9},
{engText : 'gurUduAwry jw',punjabiText: 'ਗੁਰੂਦੁਆਰੇ ਜਾ',meaning:'Go to Gurudwara',level:9},
{engText : 'hrw rumwl PV',punjabiText: 'ਹਰਾ ਰੁਮਾਲ ਫੜ',meaning:'Hold the Green Handkerchief',level:9},
{engText : 'bwNdr kylw Kw',punjabiText: 'ਬਾਂਦਰ ਕੇਲਾ ਖਾ',meaning:'Monkey eat Banana',level:9},
{engText : 'im`qr syb Kw',punjabiText: 'ਮਿੱਤਰ ਸੇਬ ਖਾ',meaning:'Friend eat Apple',level:9},
{engText : 'kwN rotI Kw',punjabiText: 'ਕਾਂ ਰੋਟੀ ਖਾ',meaning:'Crow eat Chapati/Roti',level:9},
{engText : 'gwN duD dy',punjabiText: 'ਗਾਂ ਦੁਧ ਦੇ',meaning:'Cow give Milk',level:9},
{engText : 'cor dOV igAw',punjabiText: 'ਚੋਰ ਦੌੜ ਗਿਆ',meaning:'Thief ran away',level:9},
{engText : 'AjIq pusqk pVH',punjabiText: 'ਅਜੀਤ ਪੁਸਤਕ ਪੜ੍ਹ',meaning:'Ajeet read the book',level:9},
{engText : 'BwlU pYdl cl',punjabiText: 'ਭਾਲੂ ਪੈਦਲ ਚਲ',meaning:'Bear walk on foot',level:9},
]