export const words = [
  { text: "ਨਾਮ", meaning: "Name, God Consciousness, Divine Presence" },
  { text: "ਰਹਾੳੁ", meaning: "Pause, (marks chorus, or main theme line)" },
  { text: "ਮਹਲਾ", meaning: "Identifies which Guru is author, neighborhood" },
  { text: "ਰਾਮ", meaning: "God, All pervading Divine Spirit" },
  { text: "ਗੁਰਮੁਖ", meaning: "In tune with the Guru" },
  { text: "ਪ੍ਰਭ", meaning: "Beloved, Master" },
  { text: "ਸਦਾ", meaning: "Always" },
  { text: "ਸਤਿਗੁਰ", meaning: "True or Perfect Guru, God" },
  {
    text: "ਜੀੳੁ",
    meaning: "soul or life; respectful and affectionate apelation (Jee in MP)",
  },
  { text: "ਬਿਨੁ", meaning: "without" },
  { text: "ਜਨ", meaning: "(devoted) servant, slave" },
  { text: "ਸਭ", meaning: "all" },
  { text: "ਮਹਿ", meaning: "in (preposition), within" },
  { text: "ਸਚੁ", meaning: "true, eternal" },
  { text: "ਕੋ", meaning: "to (pp - noo in MP), any or which (koee in MP)" },
  { text: "ਸਬਦਿ", meaning: "Word, Naam" },
  { text: "ਸੁਖ", meaning: "happiness, peace" },
  {
    text: "ਮਾਿੲਅਾ",
    meaning: "worldly entanglements, illusionary & transient",
  },
  { text: "ਸੰਗ", meaning: "with, close" },
  { text: "ਹੳੁ", meaning: "I or me (pronoun)" },
  { text: "ਪਰਸਾਦ", meaning: "grace, kindness, mercy" },
  { text: "ਸੋੲੀ", meaning: "that one" },
  { text: "ਕਿਰਪਾ", meaning: "kindness, mercy" },
  {
    text: "ਸੰਤ",
    meaning: "saintly person in tune with God, often used for Guru",
  },
  { text: "ਅੰਤਰ", meaning: "within, in (MP - vich)" },
  { text: "ਭਗਤ", meaning: "devotee of God, saintly person" },
  { text: "ਸਿੳੁ", meaning: "(pp) to, with (MP - noo)" },
  { text: "ਕਿਅਾ", meaning: "what (MP - kee)" },
  { text: "ਸਗਲ", meaning: "all" },
  {
    text: "ਹਉਮੈ",
    meaning:
      "ego, pride, sense of I (separate from God & creation or from others)",
  },
  { text: "ਪਾੲੀਅੈ", meaning: "obtain" },
  { text: "ਹੇ", meaning: "O (form of address)" },
  { text: "ਘਰ", meaning: "home" },
  { text: "ਸ਼ਬਦ", meaning: "Word, Gurbani, Naam" },
  { text: "ਮਿਲ", meaning: "meet" },
  { text: "ਹਮ", meaning: "We, I" },
  { text: "ਕਹੁ", meaning: "says, say \xa0(kehna - to say)" },
  { text: "ਦੁਖ", meaning: "sorrow, suffering" },
  { text: "ਆਵੈ", meaning: "comes (aanaa, aavnaa - to come)" },
  { text: "ਭਾੲੀ", meaning: "brother, friend (used as address)" },
  {
    text: "ਸੁਆਮੀ",
    meaning: "Master, Lord, Husband; (syn - thakur) (MP- maalik)",
  },
  { text: "ਆਸਾ", meaning: "hope, desire" },
  { text: "ਸਰਬ", meaning: "all" },
  { text: "ਤਨ", meaning: "body" },
  { text: "nit", meaning: "daily - (MP - roz) (syn andin)" },
  { text: "ਭਾਵੈ", meaning: "to ge pleasing, appeal to" },
  { text: "ਪਾੲੀਅੈ", meaning: "obtain" },
  { text: "ਭੲੇ", meaning: "become" },
  { text: "ਪੂਰਨ", meaning: "complete, perfect" },
  { text: "ਰਸ", meaning: "delicious taste, enjoyment, spiritual rapture" },
  { text: "ਲਿਵ", meaning: "deep continuous love and absorption" },
  { text: "ਫਿਰ", meaning: "again" },
  { text: "ਸੇਵਾ", meaning: "service" },
  { text: "ਜਨਮ", meaning: "birth" },
  { text: "ਜੀਅ", meaning: "living being, tongue, soul" },
  { text: "ਬਾਣੀ", meaning: "speech, Word" },
  {
    text: "ਸਹਜਿ",
    meaning:
      "state of peace and balance, tranquility, spontaneous, naturally - with the flow, in tune with the Infinite",
  },
  { text: "ਨਾਉ", meaning: "Naam, name" },
  { text: "ਏਕ", meaning: "one (MP - ik)" },
  { text: "ਕਰਹਿ", meaning: "karnaa - to do" },
  { text: "ਆਇਆ", meaning: "aanaa - to come" },
  { text: "ਕਰਮ", meaning: "grace, action" },
  { text: "ਰੰਗ", meaning: "dye, love" },
  { text: "ਅਨਦਿਨੁ", meaning: "daily" },
  { text: "ਚਰਨ", meaning: "feet - symbolizes devotion, humility" },
  { text: "ਅਮਰਿਤ", meaning: "nectar, immortality" },
  { text: "ਦੁਖ", meaning: "suffering, unhappiness" },
  { text: "ਸਾਧ", meaning: "saintly person," },
  { text: "ਕੀਆ", meaning: "action, (MP - keeta)" },
  { text: "ਕਰਤਾ", meaning: "creator" },
  { text: "ਪੑੀਤ", meaning: "love" },
  { text: "ਅਵਰੁ", meaning: "other" },
  { text: "ਭਾਇ", meaning: "pleases; will; love (doojaa bhaai - duality)" },
  { text: "ਵਸੈ", meaning: "live, abide" },
  { text: "ਵਿਚ", meaning: "in, within" },
  { text: "ਮਤ", meaning: "wisdom, not" },
  { text: "ਪਿਅਾਰੇ", meaning: "beloved" },
  { text: "ਪੁਰਖ", meaning: "person, being, God" },
  { text: "ਜਮ", meaning: "death, messenger of death" },
  { text: "ਵਡਿਆਈ", meaning: "greatness, glory" },
  { text: "ਕੋਁਟ", meaning: "millions (lit. 10 million)" },
  { text: "ਮਹਾ", meaning: "great" },
  { text: "ਜੋਤ", meaning: "light" },
  { text: "ਹਿਰਦੈ", meaning: "(in the) heart, mind (MP - dil) abbrev: ridai" },
  { text: "ਨਿਰਮਲ", meaning: "pure (mal=impurity)" },
  { text: "ਭੈ", meaning: "fear ; syn - bhau" },
  { text: "ਨਦਰ", meaning: "grace" },
  { text: "ਦੂਜਾ", meaning: "second, other, duality" },
  { text: "ਪਤ", meaning: "honor" },
  { text: "ਗੁਰਮਤ", meaning: "the Guru's teaching, wisdom" },
  { text: "ਮੁਖ", meaning: "mouth, face, word" },
  { text: "ਬਲ", meaning: "strenght, power; sacrifice (balihaaree)" },
  { text: "ਭਉ", meaning: "fear (bhaao - love)" },
  { text: "ਭਗਤ", meaning: "devotee of God, saintly person" },
  { text: "ਦਾਤਾ", meaning: "giver," },
  { text: "ਗਤ", meaning: "state, emancipation" },
  { text: "ਦਾਸ", meaning: "(devoted) servant, slave" },
  { text: "ਦਇਆਲ", meaning: "kind, generous" },
  { text: "ਮਨਮੁਖ", meaning: "self-willed, (opp. of Gurmukh)" },
  { text: "ਸਤ", meaning: "truth" },
  { text: "ਬਿਧ", meaning: "Method, way" },
  { text: "ਸਮਾਇ", meaning: "absorbed in" },
  { text: "ਜਗ", meaning: "world" },
  { text: "ਦਰ", meaning: "door, portal" },
  {
    text: "ਅਗਮ",
    meaning: "incomprehensible (attribute of God); unapproachable",
  },
  { text: "ਹੁਕਮ", meaning: "command, will" },
  { text: "ਕਮਲ", meaning: "lotus" },
  { text: "ਠਾਕੁਰ", meaning: "Master" },
  { text: "ਜਬ", meaning: "when" },
  { text: "ਚਿਤ", meaning: "mind, heart" },
  { text: "ਇਹ", meaning: "this" },
  { text: "ਦਾਨ", meaning: "charity, gift" },
  { text: "ਬਿਖ", meaning: "poison, sin" },
  { text: "ਧਨ", meaning: "wealth; blessed; wife or woman" },
  { text: "ਮੇਲ", meaning: "union; melnaa - to unite" },
  { text: "ਦਰਗਿਹ", meaning: "court" },
  { text: "ਗਿਆਨ", meaning: "knowledge, realization" },
  { text: "ਮਰੈ", meaning: "dies (marnaa - to die)" },
  { text: "ਰਤੇ", meaning: "steeped, absorbed" },
  { text: "ਦਿਨ", meaning: "day" },
  { text: "ਅਤ", meaning: "very" },
  {
    text: "ਸਿਮਰ",
    meaning: "remember with love, hold in your heart, meditate",
  },
  { text: "ਅਦਰ", meaning: "in, within" },
  {
    text: "ਮੋਹ",
    meaning:
      "attachment, excessive unhealthy love; mohnaa - to attract or fascinate",
  },
  { text: "ਨਿਧ", meaning: "treasure" },
  { text: "ਸਾਧਸਗਤ", meaning: "holy company" },
  { text: "ਲਿਖਿਆ", meaning: "written, destined (likhna- to write)" },
  { text: "ਮਰ", meaning: "marnaa - to die; janam maran = birth & death" },
  { text: "ਦੀਨ", meaning: "poor, humble; religion, spiritual world" },
  { text: "ਜਸ", meaning: "glory" },
  { text: "ਧਿਆਇਆ", meaning: "meditate on, remember, repeat name" },
  { text: "ਘਟ", meaning: "vessel, heart, being" },
  { text: "ਜਉ", meaning: "if" },
  { text: "ਪੰਚ", meaning: "five, select" },
  { text: "ਗੋਬਿਦ", meaning: "God (var - Govind, Govinda)" },
  { text: "ਪਾਪ", meaning: "sin" },
  { text: "ਪਾਰ", meaning: "beyond, other shore" },
  { text: "ਸਾਹਿਬ", meaning: "Master, lord, term of respect" },
  { text: "ਦਇਆ", meaning: "mercy" },
  { text: "ਕਹਾ", meaning: "where" },
  { text: "ਮਾਰ", meaning: "kill" },
  { text: "ਰਸਨਾ", meaning: "tongue, speech" },
  { text: "ਧੁਰ", meaning: "destined, primal" },
  { text: "ਭੀ", meaning: "also (MP: vee)" },
  { text: "ਭਉ", meaning: "love" },
  { text: "ਤਬ", meaning: "then" },
  { text: "ਪਾਰਬੵਹਮ", meaning: "God, Transcendental Reality" },
  { text: "ਪਿਰ", meaning: "Divine Spouse" },
  { text: "ਨਿਧਾਨ", meaning: "treasure" },
  { text: "ਛੋਡ", meaning: "abandon, leave" },
  { text: "ਸਗਤ", meaning: "association, company" },
  { text: "ਵਡਭਾਗੀ", meaning: "fortunate" },
  { text: "ਤਤ", meaning: "sublime essence" },
  { text: "ਪਰਮ", meaning: "supreme" },
  { text: "ਕੀਮਤ", meaning: "price, value" },
  { text: "ਬਾਹਰ", meaning: "outside, besides" },
  { text: "ਤਿਸਨਾ", meaning: "thirst, desire" },
  { text: "ਕਾਮ", meaning: "lust, physical pleasures" },
  { text: "ਦਰਸਨ", meaning: "vision, experience of being in Presence" },
  { text: "ਜਲ", meaning: "water (mp - paanee)" },
  { text: "ਪਾਵਿਹ", meaning: "paavna - to obtain" },
  { text: "ਮਸਤਕ", meaning: "Forehead (MP mathaa)" },
  { text: "ਭਰਮ", meaning: "doubt, confusion" },
  { text: "ਕਾਇਆ", meaning: "body, self" },
  { text: "ਪਰੀਤਮ", meaning: "beloved" },
  { text: "ਮੈਲ", meaning: "impurity" },
  { text: "ਵਸਿਆ", meaning: "dwells" },
  { text: "ਪਰੇਮ", meaning: "love" },
  { text: "ਅਗਨ", meaning: "fire" },
  { text: "ਧਰਮ", meaning: "righteous actions, duty, religion" },
  { text: "ਬੵਰਮ", meaning: "Absolute Lord" },
  { text: "ਦੀਆ", meaning: "gave" },
  { text: "ਬਹੁਤ", meaning: "much, lots, very" },
  { text: "ਫਲ", meaning: "fruit" },
  { text: "ਊਪਰ", meaning: "on, above" },
  { text: "ਨਿਰਭਉ", meaning: "free from fear" },
  { text: "ਗਿਆਨੀ", meaning: "wise, knowledgable" },
  { text: "ਅਰ", meaning: "and" },
  { text: "ਜਤ", meaning: "being, creature" },
  { text: "ਕਾਰ", meaning: "task, affair" },
  { text: "ਨਰ", meaning: "Man, mortal" },
  { text: "ਸੋਭਾ", meaning: "glory" },
  { text: "ਮਾਨ", meaning: "pride, honor" },
  { text: "ਬੇਦ", meaning: "Vedas (hindu scripture)" },
  { text: "ਖਿਨ", meaning: "moment, instant" },
  { text: "ਪਰਾਨ", meaning: "life, breath" },
  { text: "ਜਲ", meaning: "water" },
  { text: "ਪਿਤਾ", meaning: "father" },
  { text: "ਜਗਤ", meaning: "world" },
  { text: "ਬਧਨ", meaning: "bonds, fetters" },
  { text: "ਜੋਗੀ", meaning: "yogi, one seeking union with God" },
  { text: "ਮੀਤ", meaning: "dear friend" },
  { text: "ਰਵ", meaning: "permeating" },
  { text: "ਅਤ", meaning: "end, limit" },
  { text: "ਕਾਲ", meaning: "death, time" },
  { text: "ਕਵਨ", meaning: "which" },
  { text: "ਰਤਨ", meaning: "gem" },
  { text: "ਕੂੜ", meaning: "false" },
  { text: "ਜਗ", meaning: "world" },
  { text: "ਸਸਾਰ", meaning: "world" },
  {
    text: "ਅੰਤਰਜਾਮੀ",
    meaning: "Knower of deepest thoughts (God), Inner Guide",
  },
  { text: "ਦੁਰਮਤ", meaning: "evil mindedness" },
  { text: "ਮਿਲਾਏ", meaning: "help to meet, unite" },
  { text: "ਸਾਗਰ", meaning: "ocean" },
  { text: "ਪਰਾਪਤ", meaning: "possess, obtain" },
  { text: "ਜਾਤ", meaning: "caste, social status, species" },
  { text: "ਕਰੋਧ", meaning: "anger, wrath" },
  { text: "ਆਠ", meaning: "eight" },
  { text: "ਗੋਪਾਲ", meaning: "God, cherisher of the world" },
  { text: "ਓਟ", meaning: "support" },
  { text: "ਪੂਜਾ", meaning: "worship" },
  { text: "ਅਰਦਾਸ", meaning: "prayer" },
  { text: "ਧੂੜ", meaning: "dust" },
  { text: "ਪਛਾਣੈ", meaning: "(pachhananaa) to recognize" },
  { text: "ਤਿਆਗ", meaning: "abandon, give up, renounce" },
  { text: "ਪਿੰਡੁ", meaning: "body" },
  { text: "ਮੀਠਾ", meaning: "sweet (MP - mitha)" },
  { text: "ਭਲਾ", meaning: "good" },
  { text: "ਮੂਰਖ", meaning: "fool" },
  { text: "ਨਿਰੰਜਨ", meaning: "God, The One unsullied by Maya or pollution" },
  { text: "ਪੇਖ", meaning: "pekhna - to see (syn. dekhna)" },
  { text: "ਕੁਲ", meaning: "clan, ancestory" },
  { text: "ਮਾਤਾ", meaning: "mother" },
  { text: "ਸਰਿਸਟ", meaning: "creation, universe" },
  { text: "ਸੁਤ", meaning: "son, child" },
  { text: "ਨਿਕਟ", meaning: "near, close" },
  { text: "ਹਮਾਰਾ", meaning: "Our, my" },
  { text: "ਊਚਾ", meaning: "high" },
  { text: "ਭਾਗ", meaning: "bhaagna - to run away; bhaag - fortune, destiny" },
  {
    text: "ਤਰੈ",
    meaning: "tarnaa -swim, be saved; taraana - to save, help to swim",
  },
  {
    text: "ਚਿੰਤਾ",
    meaning: "worry (MP - fikar) (achintaa - free from worry)",
  },
  { text: "ਨਾਰੀ", meaning: "woman, wife" },
  { text: "ਕਲਾ", meaning: "art, technique" },
  { text: "ਲੋਭ", meaning: "greed" },
  { text: "ਸਮਰਥ", meaning: "potent, capable" },
  { text: "ਖਸਮ", meaning: "master, God" },
  { text: "ਮਿਤ", meaning: "measure (n)" },
  {
    text: "ਸੇਜ",
    meaning:
      "bed; divine bed representing union between God and the soul bride",
  },
  { text: "ਪਗ", meaning: "foot" },
  { text: "ਬਾਾਤ", meaning: "story, issue, conversation (syn. Gal)" },
  { text: "ਭੰਡਾਰੁ", meaning: "warehouse, treasure" },
  { text: "ਕਾਰਜ", meaning: "affair, task" },
  { text: "ਭਰਪੂਰ", meaning: "completely full" },
  { text: "ਉਪਦੇਸ", meaning: "teachings, preaching" },
  { text: "ਗਰਭ", meaning: "womb" },
  { text: "ਸਰੀਰ", meaning: "body, self" },
  { text: "ਬਿਅੰਤੁ", meaning: "infinite; without an end" },
  { text: "ਬਿਧਾਤਾ", meaning: "architect of destiny, God" },
  { text: "ਮਨੋਰਥ", meaning: "hope, desire" },
  { text: "ਅਵਗੁਨ", meaning: "sin, weakness" },
  { text: "ਸਿ", meaning: "praise, glory" },
  { text: "ਭੰਜਨੁ", meaning: "destroyer" },
  { text: "ਬੇਨਤੀ", meaning: "prayer, request" },
  { text: "ਜੋਰ", meaning: "power, to join (jorna)" },
  { text: "ਨਿਰੰਕਾਰੁ", meaning: "The Formless One, God" },
  { text: "ਪਰਗਾਸ", meaning: "Light, enlightenment" },
  { text: "ਵਿਕਾਰ", meaning: "sins, evil" },
  { text: "ਉਧਾਰੇ", meaning: "udharnaa - to be liberated" },
  { text: "ਵਸਿਆ", meaning: "vasnaa - to live, abide, be enshrined" },
  { text: "ਪਦਾਰਥ", meaning: "substance, essence, treasure" },
  { text: "ਭਾਰ", meaning: "full, overflowing" },
  { text: "ਉਪਾਵ", meaning: "effort, way or solution" },
  { text: "ਵਾਜੈ", meaning: "rings, play as of music" },
  { text: "ਠਉਰ", meaning: "Sanctuary, place of rest, support" },
  { text: "ਸੰਗੀ", meaning: "companion" },
  { text: "ਆਗਿਆ", meaning: "command, direction" },
  { text: "ਊਜਲ", meaning: "bright, pure" },
  { text: "ਸਮਾਲੈ", meaning: "cherish, take care of, remember" },
  { text: "ਜਪ", meaning: "repeat Name, medidate" },
  { text: "ਸਾਸ", meaning: "breath" },
  { text: "ਮੋਹਿਆ", meaning: "mohanaa- to fascinate, attract" },
  { text: "ਵਿਸਾਰ", meaning: "forget; MP - bhulnaa" },
  {
    text: "ਨਿਰਗੁਣ",
    meaning: "without any merit; absolute and unmanifested (God)",
  },
  {
    text: "ਪਰਾਈ",
    meaning: "stranger, not one of us, belonging to someone else",
  },
  { text: "ਸਿਆਨਪ", meaning: "cleverness, wisdom" },
  { text: "ਕੁਰਬਾਨ", meaning: "sacrifice" },
  { text: "ਚਾਨਨ", meaning: "light" },
  { text: "ਧਾਵਤ", meaning: "running (dhaavnaa - to run)" },
  {
    text: "ਪ੍ਰਤਿਪਾਲ",
    meaning: "cherish, take care of (pratipalak - cherisher)",
  },
  { text: "ਸਵਾਰ", meaning: "to set right, decorate," },
  { text: "ਅਧਾਰ", meaning: "support" },
  { text: "ਬੂਝੈ", meaning: "(v) understands" },
  { text: "ਬਿਗਸੈ", meaning: "blooms forth, joyous, radiant" },
  { text: "ਜਾਨੌ", meaning: "jananaa - to know" },
  { text: "ਰਾਖਾ", meaning: "Protector (rakhshaa - protection), caretaker" },
  { text: "ਸਰਨ", meaning: "shelter, protection (var. sharan, sarnaaee)" },
  { text: "ਰਹੋ", meaning: "stay, remain" },
  { text: "ਚਤੁਰ", meaning: "clever, intelligent" },
  { text: "ਘਨੇਰੇ", meaning: "lots, great" },
  { text: "ਸਾਜੇ", meaning: "fashions, creates" },
  { text: "ਦਰਦ", meaning: "Pain, suffering" },
  { text: "ਊਠਤ", meaning: "while rising, standing; MP - uthnaa" },
  { text: "ਬ੍ਰਹਮੰਡ", meaning: "universe" },
  { text: "ਅਪਰਾਧੀ", meaning: "sinner, guilty" },
  { text: "ਗਲ", meaning: "thing, talk" },
  { text: "ਸੋਵਤ", meaning: "sleeping; sovana - to sleep" },
  { text: "ਕੀਰਤਨ", meaning: "singing praises, spiritual music" },
  { text: "ਗਰੀਬ", meaning: "poor, humble" },
  { text: "ਆਟਲ", meaning: "eternal" },
  { text: "ਸਿਆਨਾ", meaning: "wise" },
  { text: "ਸੁਮਤ", meaning: "sublime wisdom" },
  { text: "ਮਾਗੈ", meaning: "asks" },
  { text: "ਵਰਨ", meaning: "n. color or caste; v. to desribe" },
  { text: "ਭਰਵਾਸਾ", meaning: "trust, confidence. Var - bharosaa" },
  { text: "ਦੇਸ", meaning: "abode, country, land" },
  { text: "ਨਮਸਕਾਰ", meaning: "salutation, bow in humility" },
  { text: "ਨੀਕਾ", meaning: "good, sublime" },
  { text: "ਅਹਕਾਰ", meaning: "pride, ego" },
  { text: "ਮੇਹਰਵਾਨ", meaning: "generous, compassionate" },
  { text: "ਸਾਥੀ", meaning: "companion" },
  { text: "ਵੈਰ", meaning: "enmity (var. bair); vairee or bairee - enemy" },
  { text: "ਆਗਿਆਕਾਰੀ", meaning: "obedient" },
  { text: "ਲਾਗ", meaning: "(laagna) -to be attached" },
  { text: "ਪਰਵਾਰ", meaning: "family" },
  { text: "ਸਵਾਰੇ", meaning: "improve" },
  { text: "ਦਲਾਲ", meaning: "kind, generous" },
  { text: "ਸਲਾਹ", meaning: "to praise" },
  { text: "ਜਾਗਨਾ", meaning: "to be awake, spiritually aware" },
  { text: "ਸਮਰਥ", meaning: "potent, capable" },
  { text: "ਅਜ", meaning: "Today" },
  { text: "ਕਟ", meaning: "Cut" },
  { text: "ਛਤ", meaning: "Roof" },
  { text: "ਥਲ", meaning: "Dry land" },
  { text: "ਅਗ", meaning: "Fire" },
  { text: "ਕਦ", meaning: "Height" },
  { text: "ਛਕ", meaning: "Eat" },
  { text: "ਦਸ", meaning: "Ten, Tell" },
  { text: "ਅਖ", meaning: "Eye" },
  { text: "ਖਪ", meaning: "Noise" },
  { text: "ਛਲ", meaning: "Cheating" },
  { text: "ਧਰ", meaning: "Put" },
  { text: "ਸਚ", meaning: "Truth" },
  { text: "ਖਟ", meaning: "Earn" },
  { text: "ਜਲ", meaning: "Water" },
  { text: "ਧਕ", meaning: "Push" },
  { text: "ਸਭ", meaning: "All" },
  { text: "ਖਲ", meaning: "Skin" },
  { text: "ਜਗ", meaning: "Jug" },
  { text: "ਨਕ", meaning: "Nose" },
  { text: "ਹਥ", meaning: "Hand" },
  { text: "ਗਲ", meaning: "Neck" },
  { text: "ਜਟ", meaning: "Farmer" },
  { text: "ਨਟ", meaning: "Nut" },
  { text: "ਹਸ", meaning: "Laugh" },
  { text: "ਗਠ", meaning: "Knot" },
  { text: "ਝਗ", meaning: "Bubbles" },
  { text: "ਪਕ", meaning: "Ripe" },
  { text: "ਹਕ", meaning: "Right" },
  { text: "ਘਰ", meaning: "House" },
  { text: "ਟਬ", meaning: "Tub" },
  { text: "ਪਗ", meaning: "Dastar" },
  { text: "ਹਲ", meaning: "Plough" },
  { text: "ਘਲ", meaning: "Send" },
  { text: "ਟਪ", meaning: "Jump" },
  { text: "ਪਰ", meaning: "But" },
  { text: "ਹੜ", meaning: "Flood" },
  { text: "ਘਟ", meaning: "Less" },
  { text: "ਠਗ", meaning: "Thug" },
  { text: "ਫਲ", meaning: "Fruit" },
  { text: "ਕਲ", meaning: "Yesterday" },
  { text: "ਚਲ", meaning: "Move" },
  { text: "ਤਕ", meaning: "See" },
  { text: "ਫੜ", meaning: "Hold" },
  { text: "ਕਪ", meaning: "Cup" },
  { text: "ਚਬ", meaning: "Chew" },
  { text: "ਤਨ", meaning: "Body" },
  { text: "ਬਸ", meaning: "Bus" },
  { text: "ਕਜ", meaning: "Cover" },
  { text: "ਚਖ", meaning: "Taste" },
  { text: "ਥਕ", meaning: "Tired" },
  { text: "ਬਲ", meaning: "Power" },
  { text: "ਅਖਰ", meaning: "Word" },
  { text: "ਕਣਕ", meaning: "Wheat" },
  { text: "ਝਗੜ", meaning: "Quarrel" },
  { text: "ਨਰਕ", meaning: "Hell" },
  { text: "ਅਰਥ", meaning: "Meaning" },
  { text: "ਖਦਰ", meaning: "Cloth" },
  { text: "ਝੜਪ", meaning: "Argument" },
  { text: "ਨਰਮ", meaning: "Soft" },
  { text: "ਸਫਰ", meaning: "Journey" },
  { text: "ਖਰਚ", meaning: "Spend" },
  { text: "ਝਖੜ", meaning: "Storm" },
  { text: "ਬਲਦ", meaning: "Bull" },
  { text: "ਸੜਕ", meaning: "Road" },
  { text: "ਗਰਮ", meaning: "Hot" },
  { text: "ਟਕਰ", meaning: "Collision" },
  { text: "ਬਰਫ਼", meaning: "Ice" },
  { text: "ਸਬਕ", meaning: "Lesson" },
  { text: "ਚਮਕ", meaning: "Shine" },
  { text: "ਢਕਣ", meaning: "Lid" },
  { text: "ਮਟਰ", meaning: "Peas" },
  { text: "ਕਮਰ", meaning: "Back" },
  { text: "ਚਪਲ", meaning: "Sandle" },
  { text: "ਦਰਦ", meaning: "Pain" },
  { text: "ਸ਼ਬਦ", meaning: "Word" },
  { text: "ਕਮਲ", meaning: "Lotus" },
  { text: "ਚਤਰ", meaning: "Clever" },
  { text: "ਧਰਮ", meaning: "Religion" },
  { text: "ਸ਼ਰਤ", meaning: "Conditional" },
  { text: "ਕਲਮ", meaning: "Pen" },
  { text: "ਜਨਮ", meaning: "Birth" },
  { text: "ਨਕਲ", meaning: "Copy" },
  { text: "ਖ਼ਬਰ", meaning: "News" },
  { text: "ਅਦਰਕ", meaning: "Ginger" },
  { text: "ਗਰਦਨ", meaning: "Neck" },
  { text: "ਦਸਖਤ", meaning: "Signature" },
  { text: "ਬਰਤਨ", meaning: "Utensils" },
  { text: "ਹਰਕਤ", meaning: "Movement" },
  { text: "ਗਲਗਲ", meaning: "Grapefruit" },
  { text: "ਦਰਜਨ", meaning: "Dozen" },
  { text: "ਮਤਲਬ", meaning: "Meaning" },
  { text: "ਹਰਮਨ", meaning: "Famous" },
  { text: "ਗੜਬੜ", meaning: "Mess up" },
  { text: "ਦਫ਼ਤਰ", meaning: "Office" },
  { text: "ਮਖ਼ਮਲ", meaning: "Velvet" },
  { text: "ਕਸਰਤ", meaning: "Exercise" },
  { text: "ਝਟਪਟ", meaning: "Instant" },
  { text: "ਨਫ਼ਰਤ", meaning: "Hate" },
  { text: "ਸ਼ਰਬਤ", meaning: "Syrup" },
  { text: "ਖਸਖਸ", meaning: "Poppy Seed" },
  { text: "ਥਰਮਸ", meaning: "Thermos" },
  { text: "ਪਰਬਤ", meaning: "Mountain" },
  { text: "ਸ਼ਲਗਮ", meaning: "Turnip" },
  { text: "ਆਸਾ", meaning: "Hope" },
  { text: "ਕਾਲਾ", meaning: "Black" },
  { text: "ਤਾਜ਼ਾ", meaning: "Fresh" },
  { text: "ਮਾਤਾ", meaning: "Mother" },
  { text: "ਆਟਾ", meaning: "Flour" },
  { text: "ਕਾਕਾ", meaning: "Child" },
  { text: "ਤਾਲਾ", meaning: "Lock" },
  { text: "ਭਾਰਾ", meaning: "Heavy" },
  { text: "ਆਰਾ", meaning: "Saw" },
  { text: "ਚਾਚਾ", meaning: "Uncle" },
  { text: "ਦਾਦਾ", meaning: "Dad's Father" },
  { text: "ਮਾਮਾ", meaning: "Mum's Brother" },
  { text: "ਸਾਰਾ", meaning: "Everything" },
  { text: "ਜਾਲਾ", meaning: "Web" },
  { text: "ਧਾਗਾ", meaning: "Thread" },
  { text: "ਰਾਜਾ", meaning: "King" },
  { text: "ਹਾਸਾ", meaning: "Laugh" },
  { text: "ਤਾਰਾ", meaning: "Star" },
  { text: "ਨਾਨਾ", meaning: "Mum's Father" },
  { text: "ਵਾਜਾ", meaning: "Harmonium" },
  { text: "ਸਾਫ਼", meaning: "Clean" },
  { text: "ਛਾਲ", meaning: "Jump" },
  { text: "ਤਾਪ", meaning: "Temperature" },
  { text: "ਯਾਦ", meaning: "Remember" },
  { text: "ਹਾਰ", meaning: "Necklace" },
  { text: "ਜਾਲ", meaning: "Net" },
  { text: "ਥਾਲ", meaning: "Plate" },
  { text: "ਯਾਰ", meaning: "Friend" },
  { text: "ਘਾਹ", meaning: "Grass" },
  { text: "ਢਾਲ", meaning: "Shield" },
  { text: "ਨਾਲ", meaning: "Beside" },
  { text: "ਰਾਜ਼", meaning: "Secret" },
  { text: "ਚਾਰ", meaning: "Four" },
  { text: "ਤਾਰ", meaning: "Wire" },
  { text: "ਬਾਲ", meaning: "Child" },
  { text: "ਲਾਲ", meaning: "Red" },
  { text: "ਚਾਹ", meaning: "Tea" },
  { text: "ਤਾਲ", meaning: "Rhythm" },
  { text: "ਬਾਗ", meaning: "Garden" },
  { text: "ਵਾਲ", meaning: "Hair" },
  { text: "ਸਦਾ", meaning: "Always" },
  { text: "ਕਟਾ", meaning: "Cut" },
  { text: "ਚਲਾ", meaning: "Drive" },
  { text: "ਫੜਾ", meaning: "Give" },
  { text: "ਸਜ਼ਾ", meaning: "Punishment" },
  { text: "ਕੜਾ", meaning: "Iron Bracelet" },
  { text: "ਜਲਾ", meaning: "Burn" },
  { text: "ਬਣਾ", meaning: "Make" },
  { text: "ਹਵਾ", meaning: "Air" },
  { text: "ਖਰਾ", meaning: "Pure" },
  { text: "ਥੜਾ", meaning: "Step" },
  { text: "ਭਰਾ", meaning: "Brother" },
  { text: "ਹਰਾ", meaning: "Green" },
  { text: "ਗਲਾ", meaning: "Throat" },
  { text: "ਪਤਾ", meaning: "Address" },
  { text: "ਰਲਾ", meaning: "Mix" },
  { text: "ਹਲਾ", meaning: "Move" },
  { text: "ਘੜਾ", meaning: "Pot" },
  { text: "ਪਲਾ", meaning: "Give Drink" },
  { text: "ਵਜਾ", meaning: "Play" },
  { text: "ਆਦਰ", meaning: "Respect" },
  { text: "ਚਾਦਰ", meaning: "Sheet" },
  { text: "ਦਾਵਤ", meaning: "Banquet" },
  { text: "ਬਾਲਕ", meaning: "Child" },
  { text: "ਸਾਬਣ", meaning: "Soap" },
  { text: "ਚਾਵਲ", meaning: "Rice" },
  { text: "ਪਾਲਕ", meaning: "Spinach" },
  { text: "ਬਾਹਰ", meaning: "Outside" },
  { text: "ਕਾਗ਼ਜ", meaning: "Paper" },
  { text: "ਚਾਨਣ", meaning: "Light" },
  { text: "ਪਾਰਕ", meaning: "Park" },
  { text: "ਮਾਲਕ", meaning: "Boss" },
  { text: "ਗਾਜਰ", meaning: "Carrot" },
  { text: "ਚਾਬਕ", meaning: "Whip" },
  { text: "ਫਾਟਕ", meaning: "Gate" },
  { text: "ਮਾਰਚ", meaning: "March" },
  { text: "ਅਨਾਰ", meaning: "Pomegranate" },
  { text: "ਸਲਾਹ", meaning: "Advice" },
  { text: "ਗਲਾਸ", meaning: "Glass" },
  { text: "ਪਲਾਟ", meaning: "Plot" },
  { text: "ਅਰਾਮ ", meaning: "Rest" },
  { text: "ਕਪਾਹ", meaning: "Cotton" },
  { text: "ਚਲਾਕ", meaning: "Clever" },
  { text: "ਮਕਾਨ", meaning: "House" },
  { text: "ਸਵਾਲ ", meaning: "Question" },
  { text: "ਕਨਾਤ", meaning: "Tent" },
  { text: "ਪਰਾਤ", meaning: "Big Bowl" },
  { text: "ਖ਼ਰਾਬ", meaning: "Bad" },
  { text: "ਹਜਾਰ", meaning: "Thousand" },
  { text: "ਕਲਾਸ", meaning: "Class" },
  { text: "ਦਵਾਤ", meaning: "Ink Pot" },
  { text: "ਖ਼ਰਾਸ਼", meaning: "Itchiness" },
  { text: "ਸਸਤਾ", meaning: "Cheap" },
  { text: "ਗਤਕਾ", meaning: "Gatka" },
  { text: "ਤਬਲਾ", meaning: "Tabla" },
  { text: "ਬਸਤਾ", meaning: "Bag" },
  { text: "ਹਲਕਾ", meaning: "Light" },
  { text: "ਗਮਲਾ", meaning: "Pot" },
  { text: "ਨਲਕਾ", meaning: "Water Pump" },
  { text: "ਭਰਨਾ", meaning: "Fill" },
  { text: "ਕਮਰਾ", meaning: "Room" },
  { text: "ਚਮਚਾ", meaning: "Spoon" },
  { text: "ਪਰਦਾ", meaning: "Curtain" },
  { text: "ਮਲਨਾ", meaning: "Rub" },
  { text: "ਕਪੜਾ", meaning: "Cloth" },
  { text: "ਝਗੜਾ", meaning: "Fight" },
  { text: "ਪਤਲਾ", meaning: "Thin" },
  { text: "ਰਸਤਾ", meaning: "Way" },
  { text: "ਅਰਦਾਸ", meaning: "Ardas" },
  { text: "ਸਮਾਚਾਰ", meaning: "News" },
  { text: "ਤਲਵਾਰ", meaning: "Sword" },
  { text: "ਪਕਵਾਨ", meaning: "Foods" },
  { text: "ਅਖ਼ਬਾਰ", meaning: "Newspaper" },
  { text: "ਹਵਾਲਾਤ", meaning: "Prison" },
  { text: "ਥਕਾਵਟ", meaning: "Tired" },
  { text: "ਪਾਠਸ਼ਾਲਾ", meaning: "School" },
  { text: "ਅਨਾਨਾਸ", meaning: "Pineapple" },
  { text: "ਟਮਾਟਰ", meaning: "Tomato" },
  { text: "ਦਸਤਾਰ", meaning: "Dastar" },
  { text: "ਮਾਸਟਰ", meaning: "Teacher" },
  { text: "ਸਰਕਾਰ", meaning: "Government" },
  { text: "ਡਾਕਟਰ", meaning: "Doctor" },
  { text: "ਦਰਬਾਰ", meaning: "Darbar" },
  { text: "ਰਫਤਾਰ", meaning: "Speed" },
  { text: "ਸਰਦਾਰ", meaning: "Sardar" },
  { text: "ਤਰਖਾਣ", meaning: "Carpenter" },
  { text: "ਪਰਵਾਰ", meaning: "Family" },
  { text: "ਵਫ਼ਾਦਾਰ", meaning: "Loyal" },
  { text: "ਇਕ", meaning: "One" },
  { text: "ਹਿਰਨ", meaning: "Deer" },
  { text: "ਗਿਣ", meaning: "Count" },
  { text: "ਦਿਲ", meaning: "Heart" },
  { text: "ਇਟ", meaning: "Brick" },
  { text: "ਹਿਲਾ", meaning: "Shake" },
  { text: "ਚਿਰ", meaning: "Long time" },
  { text: "ਪਿਤਾ", meaning: "Father" },
  { text: "ਸਿਰ", meaning: "Head" },
  { text: "ਕਿਤਾਬ", meaning: "Book" },
  { text: "ਦਿਨ", meaning: "Day" },
  { text: "ਮਿਰਚ", meaning: "Chilli" },
  { text: "ਸੀਟੀ", meaning: "Whistle" },
  { text: "ਗੀਲਾ", meaning: "Wet" },
  { text: "ਨੀਲਾ", meaning: "Blue" },
  { text: "ਮਈ", meaning: "May" },
  { text: "ਕੀੜੀ", meaning: "Ant" },
  { text: "ਤੀਰ", meaning: "Arrow" },
  { text: "ਪੀਣਾ", meaning: "Drink" },
  { text: "ਮਾਸੀ", meaning: "Mum's Sister" },
  { text: "ਖੀਰਾ", meaning: "Cucumber" },
  { text: "ਦਹੀ", meaning: "Yogurt" },
  { text: "ਪੀਲਾ", meaning: "Yellow" },
  { text: "ਵੀਰ", meaning: "Brother" },
  { text: "ਸਿਰਾ", meaning: "An End" },
  { text: "ਸੀਰਾ", meaning: "Syrup" },
  { text: "ਪਿਤਾ", meaning: "Father" },
  { text: "ਪੀਤਾ", meaning: "Drink" },
  { text: "ਹਿਲਾ", meaning: "Shake" },
  { text: "ਹੀਲਾ", meaning: "Way Out" },
  { text: "ਪਿਲਾ", meaning: "Give Water" },
  { text: "ਪੀਲਾ", meaning: "Yellow" },
  { text: "ਚਿਰ", meaning: "So Long" },
  { text: "ਚੀਰ", meaning: "Sawn" },
  { text: "ਭਿੜ", meaning: "Quarell" },
  { text: "ਭੀੜ", meaning: "Crowd" },
  { text: "ਤਿਲ", meaning: "Seed" },
  { text: "ਤੀਲ", meaning: "Match Stick" },
  { text: "ਮਿਲ", meaning: "Mill" },
  { text: "ਮੀਲ", meaning: "Mile" },
  { text: "ਉਠ", meaning: "Stand" },
  { text: "ਕੁਰਸੀ", meaning: "Chair" },
  { text: "ਜੁੱਤੀ", meaning: "Shoe" },
  { text: "ਪੁਛ", meaning: "Ask" },
  { text: "ਸੁਣ", meaning: "Listen" },
  { text: "ਗੁੱਸਾ", meaning: "Angry" },
  { text: "ਟੁਟੀ", meaning: "Broken" },
  { text: "ਪੁਲ", meaning: "Bridge" },
  { text: "ਹੁਣ", meaning: "Now" },
  { text: "ਗੁਲਾਬ", meaning: "Rose" },
  { text: "ਤੁਹਾਡਾ", meaning: "Yours" },
  { text: "ਰੁਮਾਲ", meaning: "Handkerchief" },
  { text: "ਊਠ", meaning: "Camel" },
  { text: "ਸੂਰਜ", meaning: "Sun" },
  { text: "ਚਾਕੂ", meaning: "Knife" },
  { text: "ਭੂਆ", meaning: "Aunt" },
  { text: "ਸੂਈ", meaning: "Needle" },
  { text: "ਗਊ", meaning: "Cow" },
  { text: "ਟੂਟੀ", meaning: "Tap" },
  { text: "ਭੂਰਾ", meaning: "Brown" },
  { text: "ਸੂਰ", meaning: "Pig" },
  { text: "ਗੁਰੂ", meaning: "Guru" },
  { text: "ਪੂਛ", meaning: "Tail" },
  { text: "ਮੂਲੀ", meaning: "Radish" },
  { text: "ਉਠ", meaning: "Stand" },
  { text: "ਊਠ", meaning: "Camel" },
  { text: "ਪੁਛ", meaning: "Ask" },
  { text: "ਪੂਛ", meaning: "Tail" },
  { text: "ਸੁਟ", meaning: "Throw" },
  { text: "ਸੂਟ", meaning: "Suit" },
  { text: "ਪੁ੍ੜੀ", meaning: "Small Pack" },
  { text: "ਪੂੜੀ", meaning: "Fried Roti" },
  { text: "ਸੁਰ", meaning: "Tune" },
  { text: "ਸੂਰ", meaning: "Pig" },
  { text: "ਭੁਰ", meaning: "Crumble" },
  { text: "ਭੂਰ", meaning: "Drizzle" },
  { text: "ਟੁਟੀ", meaning: "Broken" },
  { text: "ਟੂਟੀ", meaning: "Tap" },
  { text: "ਭੁਰੀ", meaning: "Crumble" },
  { text: "ਭੂਰੀ", meaning: "Brown" },
  { text: "ਸੇਬ", meaning: "Apple" },
  { text: "ਸਵੇਰਾ", meaning: "Morning" },
  { text: "ਜੇਬ", meaning: "Pocket" },
  { text: "ਨੇੜੇ", meaning: "Near" },
  { text: "ਸਾਡੇ", meaning: "Ours" },
  { text: "ਕੇਲਾ", meaning: "Banana" },
  { text: "ਤੇਲ", meaning: "Oil" },
  { text: "ਮੇਲਾ", meaning: "Fair" },
  { text: "ਸੇਵਾ", meaning: "Charity" },
  { text: "ਛੇਤੀ", meaning: "Quick" },
  { text: "ਦੇਰ", meaning: "Late" },
  { text: "ਰੇਲ", meaning: "Train" },
  { text: "ਐਤਵਾਰ", meaning: "Sunday" },
  { text: "ਸਵੈਟਰ", meaning: "Pullover" },
  { text: "ਪੈਸੇ", meaning: "Money" },
  { text: "ਬੈਲ", meaning: "Ox" },
  { text: "ਐਨਕ", meaning: "Glasses" },
  { text: "ਕੈਮਰਾ", meaning: "Camera" },
  { text: "ਪੈਦਲ", meaning: "On Foot" },
  { text: "ਭੈਣ", meaning: "Sister" },
  { text: "ਸੈਰ", meaning: "Walk" },
  { text: "ਥੈਲਾ", meaning: "Bag" },
  { text: "ਪੈਰ", meaning: "Feet" },
  { text: "ਮੈਲਾ", meaning: "Dirty" },
  { text: "ਬੇਲ", meaning: "Bail" },
  { text: "ਬੈਲ", meaning: "Ox" },
  { text: "ਮੇਲ", meaning: "Meet" },
  { text: "ਮੈਲ", meaning: "Dirt" },
  { text: "ਮੇਚ", meaning: "Fitting" },
  { text: "ਮੈਚ", meaning: "Match" },
  { text: "ਵੇਰ", meaning: "Once" },
  { text: "ਵੈਰ", meaning: "Enemity" },
  { text: "ਸੋਫਾ", meaning: "Sofa" },
  { text: "ਗੋਲ", meaning: "Round" },
  { text: "ਜੋੜੇ", meaning: "Shoes" },
  { text: "ਤੋਤਾ", meaning: "Parrot" },
  { text: "ਕੋਲ", meaning: "Near" },
  { text: "ਘੋਲ", meaning: "Wrestling" },
  { text: "ਠੋਡੀ", meaning: "Chin" },
  { text: "ਦੋ", meaning: "Two" },
  { text: "ਖੋਤਾ", meaning: "Donkey" },
  { text: "ਚੋਰ", meaning: "Thief" },
  { text: "ਢੋਲ", meaning: "Drum" },
  { text: "ਧੋਣਾ", meaning: "Wash" },
  { text: "ਔਖਾ", meaning: "Hard" },
  { text: "ਸੌਖਾ", meaning: "Easy" },
  { text: "ਕੌਲੀ", meaning: "Dish" },
  { text: "ਨੌਕਰ", meaning: "Servant" },
  { text: "ਔਰਤ", meaning: "Woman" },
  { text: "ਹੌਲੀ", meaning: "Slow" },
  { text: "ਕੌੜੀ", meaning: "Bitter" },
  { text: "ਪੌੜੀ", meaning: "Ladder" },
  { text: "ਸੌ", meaning: "Hundred" },
  { text: "ਕੌਰ", meaning: "Kaur" },
  { text: "ਦੌੜ", meaning: "Race" },
  { text: "ਫੌਜੀ", meaning: "Soldier" },
  { text: "ਸੋ", meaning: "So" },
  { text: "ਸੌ", meaning: "Hundred" },
  { text: "ਚੋਰੀ", meaning: "Theft" },
  { text: "ਚੌਰੀ", meaning: "Chourrie" },
  { text: "ਕੋਲ", meaning: "Near" },
  { text: "ਕੌਲ", meaning: "Promise" },
  { text: "ਧੋਣ", meaning: "Wash" },
  { text: "ਧੌਣ", meaning: "Neck" },
  { text: "ਘੋਲ", meaning: "Wrestling" },
  { text: "ਘੌਲ", meaning: "Mix" },
  { text: "ਭੋਰ", meaning: "Crumble" },
  { text: "ਭੌਰ", meaning: "Bumble Bee" },
  { text: "ਆਗਿਆ", meaning: "permission, command, direction" },
  { text: "ਆਗਿਆਕਾਰੀ", meaning: "obedient" },
  { text: "ਆਇਆ", meaning: "to come (aanaa)" },
  { text: "ਆਲਸ", meaning: "lazy, idle, slow, indolent, slothful, lethargic" },
  { text: "ਆਸਾ", meaning: "hope, desire" },
  { text: "ਅਸਥਾਨਿ", meaning: "place of; settlement of" },
  { text: "ਆਠ", meaning: "eight" },
  { text: "ਆਵੈ", meaning: "comes (aanaa, aavnaa - to come)" },
  {
    text: "ਅਚਰਜ",
    meaning: "Amazing, astonishing, wonderful, marvellous, strange",
  },
  { text: "ਅਘਾਇ", meaning: "Quenched, fulfilled, satisfied, contented" },
  { text: "ਅਧਾਰ", meaning: "support" },
  {
    text: "ਅਗਮ",
    meaning: "incomprehensible (attribute of God); unapproachable",
  },
  { text: "ਅਗਨਿ", meaning: "fire" },
  {
    text: "ਅਗਿਆਨੀ",
    meaning:
      "one without knowledge, illiterate, rustic, ignorant, foolish, thoughtless",
  },
  { text: "ਅਹੰਕਾਰ", meaning: "pride, ego" },
  {
    text: "ਅਲੇਪ",
    meaning: "clean, pure, untouched, untainted, opposite of ਲੇਪ s\xa0 layp",
  },
  { text: "ਅਨਾਦਿ", meaning: "without the root/soul/vibration;" },
  { text: "ਅਨਦ", meaning: "Joy, happy, delight, bliss" },
  {
    text: "ਅੰਚਲਿ",
    meaning:
      "support of a scarf or hem of skirt/dress/shirt or edge of garment",
  },
  { text: "ਅੰਧ", meaning: "blind, dark" },
  { text: "ਅੰਦਰ", meaning: "in, within" },
  { text: "ਅਨਿਕ", meaning: "many (var. anek)" },
  { text: "ਅੰਤਿ", meaning: "end, limit" },
  { text: "ਅੰਤਰ", meaning: "within, in (MP - vich)" },
  {
    text: "ਅੰਤਰਜਾਮੀ",
    meaning:
      "Knower of deepest thoughts (God), Inner Guide, Inner knower, searcher of hearts (Antar-inner Jaami-knower)",
  },
  { text: "ਅਪੜਿ", meaning: "Reach, equal, compare, approach" },
  {
    text: "ਅਪਰਾਧ",
    meaning: "Sin, blemish, fault, crime, offence, transgression.",
  },
  { text: "ਅਪਰਾਧੀ", meaning: "sinner, guilty" },
  { text: "ਅਰਦਾਸਿ", meaning: "prayer, supplication" },
  { text: "ਅਤਿ", meaning: "very" },
  { text: "ਅਟਲ", meaning: "eternal" },
  { text: "ਅਵਗਨ", meaning: "sin, weakness" },
  { text: "ਬਾਹਰਿ", meaning: "outside, besides" },
  { text: "ਬਾਂਛਹਿ", meaning: "to ask; to desire;" },
  { text: "ਬਾਣਿ", meaning: "1. Gurbani, Hymn, Sound, 2. arrow 3. morning" },
  {
    text: "ਬਾਣੀ",
    meaning: "speech, Word, Holy word, Science of sacred vibration",
  },
  { text: "ਬਾਰਿਕ", meaning: "child" },
  { text: "ਬਾਤ", meaning: "story, issue, conversation (syn. Gal)" },
  { text: "ਬਲ", meaning: "strength, power; sacrifice (balihaaree)" },
  { text: "ਬੰਧਨ", meaning: "bonds, fetters" },
  {
    text: "ਬੇਅੰਤ",
    meaning: "infinite; without an end (be-without ant-limit)",
  },
  {
    text: "ਬੀਚਾਰਾ",
    meaning: "reflect, consider, contemplate, realise, idea, opinion",
  },
  { text: "ਬੀਧੇ", meaning: "entwined, united, pierced" },
  { text: "ਬੇਨਤੀ", meaning: "prayer, request" },
  { text: "ਭਾਈ", meaning: "brother, friend (used as address)" },
  { text: "ਭਾਗ", meaning: "bhaagna - to run away; bhaag - fortune, destiny" },
  { text: "ਭਾਗਠ", meaning: "fortunate, happy, fortunate ones, flourish" },
  { text: "ਭਾਇ", meaning: "pleases; will; love (doojaa bhaai - duality)" },
  { text: "ਭਾਣਾ", meaning: "Will\t, Divine Law" },
  { text: "ਭਾਉ", meaning: "love" },
  { text: "ਭਾਵੈ", meaning: "to be pleasing, appeal to" },
  { text: "ਭਈ", meaning: "become" },
  { text: "ਭਗਤਿ", meaning: "devotee of God, saintly person" },
  {
    text: "ਭਗਤੀ",
    meaning: "devotion, worship, praying; meditation, dedication",
  },
  {
    text: "ਭਲੀ",
    meaning:
      "good, noble, positive, pious, virtuous; good turn, goodness; welfare, well being;",
  },
  { text: "ਭਰਵਾਸਾ", meaning: "Trust, confidence, support" },
  { text: "ਭੀ", meaning: "also, too, even, is" },
  { text: "ਬਿਨਾ", meaning: "without, except, but for" },
  {
    text: "ਬਿਨਸ",
    meaning: "kill, destroy, perish, merge away, end, eliminate",
  },
  { text: "ਬਿਨਸਿਆ", meaning: "dispelled, removed, destroyed, eliminated" },
  { text: "ਬਿਰਹ", meaning: "separation; isolation; alienation" },
  { text: "ਭੈ", meaning: "fear (syn - bhau)" },
  { text: "ਭਲਾ", meaning: "good, good will, positive state of being" },
  { text: "ਭੰਡਾਰ", meaning: "warehouse, treasure" },
  { text: "ਭੰਜਨ", meaning: "destroyer" },
  { text: "ਭਰਿ", meaning: "full, overflowing" },
  { text: "ਭਰਪੂਰ", meaning: "completely full" },
  { text: "ਭਰਵਾਸਾ", meaning: "trust, confidence. (Var - bharosaa)" },
  { text: "ਭਉ", meaning: "fear (bhaao - love)" },
  { text: "ਭੀ", meaning: "also (MP: vee)" },
  { text: "ਬਿਧਿ", meaning: "Method, way" },
  { text: "ਬਿਧਾਤਾ", meaning: "architect of destiny, God" },
  { text: "ਬਿਗਸੈ", meaning: "blooms forth, joyous, radiant" },
  { text: "ਬੂਝੈ", meaning: "understands" },
  { text: "ਚਰਨ", meaning: "feet - symbolizes devotion, humility" },
  { text: "ਛੋਡਿ", meaning: "abandon, leave" },
  {
    text: "ਚਿੰਤ",
    meaning: "anxiety, apprehension (opposite is ਅਚਿੰਤ s\xa0 aachint)",
  },
  {
    text: "ਚਿੰਤਾ",
    meaning: "worry (MP - fikar) (achintaa - free from worry)",
  },
  { text: "ਦਾ", meaning: "of, belonging to" },
  { text: "ਦਾਸ", meaning: "servant, slave; devoted" },
  { text: "ਦਾਤਾ", meaning: "giver" },
  { text: "ਦਇਆ", meaning: "mercy" },
  { text: "ਦਇਆਲ", meaning: "kind, generous" },
  { text: "ਦਰ", meaning: "door, portal" },
  { text: "ਦਰਗਹ", meaning: "court" },
  {
    text: "ਦਰਸਨ",
    meaning: "blessing, vision, experience of being in Presence",
  },
  {
    text: "ਦੇਖਣਹਾਰੇ",
    meaning:
      "is/are watching from 2 roots - daykhan ਦੇਖਣ s\xa0 and haaray ਹਾਰੇ s\xa0. The word dayk means look/watch; daykhan means is/are looking/watching. Haaray means doer or endower of or worthy of  the suffix.",
  },
  { text: "ਦੀਆ", meaning: "gave" },
  { text: "ਦੀਜੈ", meaning: "give, provide, grant, offer, bless, bestow" },
  { text: "ਦੀਨ", meaning: "poor, humble; religion, spiritual world" },
  { text: "ਦੀਸਹਿ", meaning: "appear, seem" },
  { text: "ਡਿਠਾ", meaning: "seen, visible" },
  { text: "ਦੇਸ", meaning: "abode, country, land" },
  { text: "ਧਾਗੈ", meaning: "relating to string or thread" },
  { text: "ਧਾਇਆ", meaning: "adopt, pursue, chase, evade," },
  {
    text: "ਧਾਰਿ",
    meaning: "keep, enshrine, arrange, secure, shower, to do, understand",
  },
  {
    text: "ਧਾਰਨਾ",
    meaning:
      "(1) determine, resolve. (2) assume, adopt, hold, bear (3) Conception",
  },
  { text: "ਧਾਵਤ", meaning: "running (dhaavnaa - to run)" },
  { text: "ਧਨ", meaning: "wealth; blessed" },
  { text: "ਡਰਿ", meaning: "fear" },
  {
    text: "ਧਰਮ",
    meaning: "righteous actions, duty, religion, path of righteousness",
  },
  { text: "ਧੀਠਾ", meaning: "Stubborn, rebellious, daring" },
  {
    text: "ਧਿਆਇਆ",
    meaning: "meditate on, remember, repeat name (MP-dhian) focus",
  },
  { text: "ਢੋਆ", meaning: "support, strength" },
  { text: "ਧੂਰਿ", meaning: "dust" },
  { text: "ਦਿਲਾਸਾ", meaning: "Comfort, consolation, solace, encouragement" },
  { text: "ਦੂਜਾ", meaning: "second, other, duality" },
  { text: "ਇਹ", meaning: "this" },
  {
    text: "ਫਾਸਾ",
    meaning: "noose, snare, death warrant, see ਫਾਹਾ s\xa0 faahaa",
  },
  {
    text: "ਫੰਧਾ",
    meaning: "chain, in chains, snare, trap, net, entanglement, noose",
  },
  { text: "ਗਾਈਝ", meaning: "to sing; should sing;" },
  { text: "ਗਤਿ", meaning: "state, emancipation" },
  { text: "ਗਲ", meaning: "thing, talk" },
  { text: "ਗਲੀ", meaning: "by talking, relating to neck" },
  { text: "ਗਰਭ", meaning: "womb" },
  { text: "ਗਰੀਬ", meaning: "poor, humble" },
  { text: "ਗੀਧੇ", meaning: "saturated, dye deeply, eagerly desire," },
  { text: "ਘਨੇਰੇ", meaning: "lots, great" },
  {
    text: "ਘੜੀ",
    meaning:
      "Moment, measure of time, watch, clock, small, pitcher or earthen pot",
  },
  { text: "ਗਿਆਨੀ", meaning: "wise, knowledgeable" },
  { text: "ਗਿਆਨ", meaning: "knowledge, realization" },
  { text: "ਗਿਰਸਤ", meaning: "1. householder. 2. engrossed" },
  {
    text: "ਗੋਬਿਦ",
    meaning: "One who sustains the world-God (var - Govind, Govinda)",
  },
  {
    text: "ਗੋਪਾਲ",
    meaning: "Cherisher of the world-God, One who rotates the Earth",
  },
  { text: "ਹਮਾਰਾ", meaning: "Our, my" },
  {
    text: "ਹਰ",
    meaning: "The Infinite (God); all, every, everyone, each, any; denominator",
  },
  { text: "ਹਰਿ", meaning: "The Infinite (God); diamond" },
  { text: "ਹਰੀ", meaning: "The Infinite (God); green" },
  { text: "ਹਉ", meaning: "I" },
  {
    text: "ਹਉਮੈ",
    meaning:
      "(hou-me, mai-I) ego, pride, sense of I (separate from God & creation)",
  },
  { text: "ਹੈ", meaning: "O (form of address)" },
  { text: "ਹੀ", meaning: "even, indeed, very, used to emphasis" },
  { text: "ਹਿਤੈ", meaning: "impelled, urged on, set in motion, placed" },
  { text: "ਹਿਰਦੈ", meaning: "(in the) heart, mind (MP - dil) abbrev: ridai" },
  { text: "ਹਮ", meaning: "We, I" },
  {
    text: "ਇਕੰਤੀ",
    meaning:
      "alone, one who loves solitude, the retired one, one who lives in seclusion from the root ਇਕ s\xa0 Ik numeral one, 1",
  },
  {
    text: "ਇਕਤ",
    meaning: "the one, the only one, together as one, collect into one",
  },
  { text: "ਜਾਝ", meaning: "goes, departs, does, happen, done, expressed" },
  { text: "ਜਾਗਨਾ", meaning: "to be awake, spiritually aware" },
  { text: "ਜਾਨਉ", meaning: "to know (jananaa )" },
  { text: "ਜਾਤਿ", meaning: "caste, social status, species" },
  { text: "ਜਬ", meaning: "when" },
  { text: "ਜਲ", meaning: "water (mp - paanee)" },
  { text: "ਜਮ", meaning: "death, god of death" },
  { text: "ਜੰਮਸੀ", meaning: "will be born, will take birth" },
  { text: "ਜਨਮ", meaning: "birth" },
  { text: "ਜੰਜੀਰ", meaning: "chain" },
  { text: "ਜੰਤ", meaning: "being, creature" },
  { text: "ਜਪ", meaning: "repeat Name, medidate, chant" },
  {
    text: "ਜੜ",
    meaning: "1. root  2. without consciousness, senseless, inanimate",
  },
  { text: "ਜਉ", meaning: "if" },
  { text: "ਜੇਤੇ", meaning: "as, just as" },
  {
    text: "ਜੀਉ",
    meaning: "soul or life; respectful and affectionate appelation (Jee in MP)",
  },
  { text: "ਜੀਵਤ", meaning: "live, living" },
  { text: "ਜੋਗੀ", meaning: "yogi, one seeking union with God" },
  {
    text: "ਜੋਨਿ",
    meaning: "incarnation, life (in birth/life cycle); species (var- joon)",
  },
  { text: "ਜੋਤਿ", meaning: "light, spiritual light" },
  { text: "ਕਾਢੇ", meaning: "1. removes, saves, liberates  2. is known" },
  { text: "ਕਾਇਆ", meaning: "body, self" },
  { text: "ਕਾਲ", meaning: "death, time" },
  { text: "ਕਾਮ", meaning: "lust, physical pleasures; work, endeaver" },
  { text: "ਕਾਰ", meaning: "task, affair" },
  { text: "ਕਾਰਜ", meaning: "affair, task" },
  {
    text: "ਕਾਟ",
    meaning:
      "Cut, bite; section, wound; deduction; act of cutting; clash; dissection, cutting",
  },
  { text: "ਕਾਟੇ", meaning: "cuts, destroys, distances" },
  {
    text: "ਕਛੂ",
    meaning: "1. Something, anything, nothing  2. Tortoise, turtle.",
  },
  { text: "ਕਦੇ", meaning: "Whenever, ever, long ago, at any time" },
  { text: "ਕਦੇ", meaning: "never, will never, shall never" },
  { text: "ਕਹਣਾ", meaning: "describe, say, tell," },
  { text: "ਕਲਾ", meaning: "art, technique" },
  { text: "ਕਲੇਸ", meaning: "agitation, grief, pain, agony, sorrow" },
  { text: "ਕਲਿ", meaning: "yesterday, tomorrow" },
  {
    text: "ਕਲਿਆਣ",
    meaning:
      "1. salvation, emancipation, success, good fortune 2. welfare, happiness, joy, comfort  3. son of Rĝga Dīpaka 4. a trend of music",
  },
  {
    text: "ਕਲਮਲ",
    meaning: "sinful, nastiness, wickedness, distress, corrupt",
  },
  {
    text: "ਕਮਾਈ",
    meaning: "Earning, work, actions, deeds, performance, accomplishment",
  },
  { text: "ਕਮਲ", meaning: "lotus" },
  {
    text: "ਕਰਮ",
    meaning:
      "action, past life actions (karma); law of cause and effect; grace",
  },
  { text: "ਕਰੇ", meaning: "to do; does" },
  { text: "ਕਰਹਿ", meaning: "to do (MP- karnaa)" },
  { text: "ਕਰਨਾ", meaning: "To do, to act, to perform" },
  { text: "ਕਰਤਾ", meaning: "creator" },
  { text: "ਕਥਨੀ", meaning: "speech, chanting, saying" },
  { text: "ਕ", meaning: "'Kakah' the sixth letter of Gurmukhi alphabet." },
  { text: "ਕੀਆ", meaning: "action (MP - keeta)" },
  { text: "ਕੀਮਤਿ", meaning: "price, value" },
  {
    text: "ਕੀਰਤਨ",
    meaning: "singing praises, spiritual music, group chanting",
  },
  { text: "ਖਾਨਦਾਨ", meaning: "Family (dynasty)" },
  { text: "ਖਸਮ", meaning: "master, God" },
  {
    text: "ਖੋਈ",
    meaning:
      "lost, forgotten, misplaced; wasted, exhausted, ruined; rid, removed",
  },
  { text: "ਕਿਆ", meaning: "what (MP - kee)" },
  { text: "ਕੋਇ", meaning: "Someone, anyone" },
  { text: "ਕੂਪ", meaning: "well, pit" },
  { text: "ਕੋਟਿ", meaning: "millions (lit. 10 million)" },
  { text: "ਲਾਗ", meaning: "to be attached (laagna)" },
  { text: "ਲੈਹਿ", meaning: "take, receive, accept" },
  {
    text: "ਲਹਨਿ",
    meaning: "1. achieve, receive, take on 2. come off, go away to a distance",
  },
  {
    text: "ਲੇਪ",
    meaning:
      "1. plaster, coat, paste, spread, layer, anoint 2. ointment, balm 3. stigma, blemish, polluted, stained, opposite of ਅਲੇਪ s\xa0 alayp",
  },
  { text: "ਲਿਖਿਆ", meaning: "written, destined (likhna- to write)" },
  { text: "ਲਿਵ", meaning: "deep continuous love and absorption" },
  { text: "ਲੋਭ", meaning: "greed" },
  { text: "ਮਇਆ", meaning: "Grace, blessing; merciful, kind; ingrained" },
  { text: "ਮਾਣਸ", meaning: "Man, human being, person" },
  { text: "ਮਾਰ", meaning: "kill" },
  {
    text: "ਮਾਰੈ",
    meaning: "kills, destroys, captures, hits; for the sake of, because of",
  },
  { text: "ਮਾਤਾ", meaning: "mother" },
  {
    text: "ਮਾਇਆ",
    meaning: "material illusion, worldly entaglements, illusionary & transient",
  },
  { text: "ਮੈਲ", meaning: "impurity" },
  { text: "ਮਹਾ", meaning: "great" },
  { text: "ਮਹਲਾ", meaning: "Identifies which Guru is author, neighborhood" },
  {
    text: "ਮਹਿਮਾ",
    meaning:
      "glory, greatness, enormity, majestic, importance, grandeur, fame, praise, tribute",
  },
  {
    text: "ਮੰਗਲ",
    meaning:
      "joy, happiness, delight, rejoice, auspiciousness, well-being, bliss, prosperity; Tuesday; the planet Mars;",
  },
  { text: "ਮੰਗਣ", meaning: "ask, beg" },
  { text: "ਮਨੋਰਥ", meaning: "hope, desire" },
  {
    text: "ਮਰਿ",
    meaning: "die (marnaa - to die); janam maran = birth & death",
  },
  { text: "ਮਾਰੈ", meaning: "dies (marnaa - to die)" },
  { text: "ਮਾਰਗ", meaning: "way, path, road" },
  {
    text: "ਮਸਤਕ",
    meaning:
      "Forehead (MP mathaa)[one's destiny is written on their forehead based on past karmas, before being incarnated]",
  },
  { text: "ਮੇਰਾ", meaning: "mine, my" },
  { text: "ਮੀਤ", meaning: "dear friend" },
  { text: "ਮੀਠਾ", meaning: "sweet (MP - mitha)" },
  { text: "ਮਹਿ", meaning: "in (postposition), within, inside" },
  { text: "ਮਿਹਰਵਾਨ", meaning: "generous, compassionate" },
  { text: "ਮੇਲ", meaning: "union; (melnaa - to unite)" },
  { text: "ਮਿਲਾਇ", meaning: "help to meet, unite" },
  { text: "ਮਿਤਿ", meaning: "measure (n)" },
  {
    text: "ਮੋਹ",
    meaning:
      "attachment, excessive unhealthy love; (mohnaa - to attract or fascinate)",
  },
  { text: "ਮੋਹਿਆ", meaning: "to fascinate, attract (mohanaa)" },
  {
    text: "ਮੂਲ",
    meaning:
      "root, base, orginal, source; original investment, capital; principal; basic, original, fundamental, primary",
  },
  {
    text: "ਮੂਰਖ",
    meaning:
      "fool, specifically someone who errs again and again but never learns",
  },
  { text: "ਨਾਲ", meaning: "1. with, near, accompany 2. tube, pipe" },
  { text: "ਨਾਲਿ", meaning: "with, near, accompany" },
  { text: "ਨਾਲੇ", meaning: "1. with, along with 2. riulets, drains" },
  {
    text: "ਨੇਮ",
    meaning: "1. code, principle, rules, rehat 2. wall, fence, enclose",
  },
  { text: "ਨਾਰੀ", meaning: "woman, wife" },
  { text: "ਨਾਉ", meaning: "*see Naam" },
  { text: "ਨਦਰਿ", meaning: "grace" },
  {
    text: "ਨਮਸਕਾਰ",
    meaning: "salutation, bow in humility, greeting, adoration",
  },
  { text: "ਨਰ", meaning: "Man, mortal" },
  {
    text: "ਨੀਕਾ",
    meaning:
      "1. good, beautiful, noble 2. pure, clean, pristine 3. food. 4. small",
  },
  { text: "ਨਿਧਿ", meaning: "treasure" },
  { text: "ਨਿਹ", meaning: "without, free from, not" },
  {
    text: "ਨਿਹਫਲ",
    meaning: "fruitless, useless (fal (ਫਲ) is fruit; nih see above)",
  },
  { text: "ਨਿਕਟਿ", meaning: "near, close" },
  {
    text: "ਨਿਰ",
    meaning: "As a prefix acts like un- in English making the meaning opposite",
  },
  { text: "ਨਿਰਭਉ", meaning: "free from fear (nir-without bhau-fear)" },
  { text: "ਨਿਰਮਲ", meaning: "pure (nir- without, mal=impurity)" },
  { text: "ਨਿਤ", meaning: "daily - (MP - roz) (syn andin), always" },
  { text: "ਊਚਾ", meaning: "high" },
  { text: "ਉਧਾਰੇ", meaning: "to be liberated (udharnaa)" },
  { text: "ਊਜਲ", meaning: "bright, pure" },
  {
    text: "ਊਂਧ",
    meaning: "upside down, overturned, inverted, turned around",
  },
  { text: "ਉਪਾਵ", meaning: "effort, way or solution" },
  { text: "ਊਪਰਿ", meaning: "on, above" },
  { text: "ਉਪਦੇਸ", meaning: "teachings, preaching" },
  { text: "ਓਟ", meaning: "support" },
  { text: "ਊਠਤ", meaning: "while rising, standing; MP - uthnaa" },
  { text: "ਪਾਈਝ", meaning: "obtain" },
  {
    text: "ਪਾਪ",
    meaning:
      "(paa:- to put, aap:- ones-self) an action against ones-self, misdeed, mistake, negative action that creates separation with the being from universality",
  },
  { text: "ਪਾਰ", meaning: "beyond, other shore" },
  { text: "ਪਾਵਹਿ", meaning: "obtain (paavna - to obtain)" },
  { text: "ਪਛਾਣੈ", meaning: "to recognize (pachhananaa)" },
  { text: "ਪਛਾਣਹਿ", meaning: "realise, recognise, understand, acknowledge" },
  {
    text: "ਪਦਾਰਥ",
    meaning:
      "wealth (material), treasure, blessing, thing, commodity, goods, provisions, riches, material object",
  },
  { text: "ਪਦਾਰਥ", meaning: "substance, essence, treasure" },
  { text: "ਪਗ", meaning: "foot" },
  { text: "ਪੰਚ", meaning: "five; select" },
  {
    text: "ਪਰਾਈ",
    meaning: "stranger, not one of us, belonging to someone else",
  },
  {
    text: "ਪਰਾਤਾ",
    meaning: "attained, seized, clung; fall, lie, sink; gaze,",
  },
  { text: "ਪਰਮ", meaning: "supreme" },
  { text: "ਪਰੋਈ", meaning: "to string, to thread, to weave" },
  { text: "ਪਰਤਾਪ", meaning: "victory, glory, splendour" },
  { text: "ਪਰਵਾਰ", meaning: "family" },
  { text: "ਪਤਿ", meaning: "honor" },
  {
    text: "ਪਤਿਵੰਤਾ",
    meaning: "honorable, respectable, from ਪਤਿ,Patt and ਵੰਤਾ vantaa",
  },
  {
    text: "ਪਤਿ",
    meaning: "1. lord, master, husband. 2. Honour, respect, reputation",
  },
  {
    text: "ਪੀਠਾ",
    meaning:
      "crushed, ground, pulses soaked in water and crushed on stone or in mortar",
  },
  { text: "ਪੇਖਿ", meaning: "see (pekhna - to see; MP dekhna)" },
  { text: "ਫਿਰਿ", meaning: "again, then" },
  { text: "ਪਿਆਰੇ", meaning: "beloved, loved one (piar-love)" },
  { text: "ਪਿੰਡ", meaning: "body" },
  { text: "ਪਿਤਾ", meaning: "father" },
  {
    text: "ਪੂਜਾ",
    meaning: "worship, prayer (Hindu traditional ceremony including offerings)",
  },
  { text: "ਪੂਰਨ", meaning: "complete, perfect" },
  {
    text: "ਪਰਕਾਸ਼",
    meaning:
      "light, radiance, illumination; clarity of vision, enlightenment, mental or spiritual awakening; opening ceremony of Guru Granth Sahib",
  },
  { text: "ਰਾਗ", meaning: "1. music, musical mode. 2. Love" },
  { text: "ਰਾਖਾ", meaning: "Protector (rakhshaa - protection), caretaker" },
  { text: "ਰਾਖਸਿ", meaning: "1. keeps (feminine) 2. Demon" },
  {
    text: "ਰਾਮ",
    meaning:
      "(1) One who resides everywhere, God, all prevading Spirit; (2) Raam Chandar - Hindu deity.",
  },
  {
    text: "ਰਹਾਉ",
    meaning:
      "Pause, command to pause in reflection of the previous line (marks chorus, or main theme line)",
  },
  { text: "ਰਹਿਆ", meaning: "is, remains, stays, pervading, contained" },
  {
    text: "ਰਹਤ",
    meaning: "1. living, way of life 2. discipline 3. without 4. separate",
  },
  { text: "ਰਹੇ", meaning: "remain, stay, keep" },
  {
    text: "ਰੰਗ",
    meaning: "color, dye; love, to be dyed in the color of love for God",
  },
  { text: "ਰਸਾ", meaning: "see ras, Juices" },
  {
    text: "ਰਸਾਲੀ",
    meaning: "juicy, full of juice, house of nectar ,from ਰਸ s\xa0 raas juice",
  },
  { text: "ਰਸਨਾ", meaning: "tongue, speech" },
  {
    text: "ਰਤਾ",
    meaning: "1. Dyed, absorbed, saturated  2. virtuous 3. tiny, minute",
  },
  { text: "ਰਤੇ", meaning: "steeped, absorbed" },
  { text: "ਰਵਿ", meaning: "permeating" },
  {
    text: "ਰਿਦੈ",
    meaning: "in/within your heart, deep within your consciousness",
  },
  { text: "ਸਾ", meaning: "1. that, she, he, God" },
  { text: "ਸਾਢੇ", meaning: "and a half" },
  { text: "ਸਾਗਰ", meaning: "ocean" },
  { text: "ਸਾਹਿਬ", meaning: "Master, lord, term of respect" },
  { text: "ਸਾਜੇ", meaning: "fashions, creates" },
  {
    text: "ਸਾਰੰਗਪਾਣੀ",
    meaning:
      "abode of the Lord; the holy lake; from 2 roots - ਸਾਰੰਗ s\xa0 see sarang and ਪਾਣੀ s\xa0 paanee - water; lake",
  },
  { text: "ਸਾਸ", meaning: "breath" },
  { text: "ਸਾਸਾ", meaning: "breath" },
  {
    text: "ਸਾਸਤ",
    meaning: "Religious text, scriptures, Shaastras, Hindu holy texts",
  },
  { text: "ਸਾਥੇ", meaning: "together, accompany, along" },
  { text: "ਸਾਥੀ", meaning: "companion" },
  { text: "ਸਾਧ", meaning: "saintly person," },
  {
    text: "ਸਬਦ",
    meaning:
      "(sha-ego, bad-breaker) sacred verse, celestial sound vibration, science of uplifting consiousness through sacred primal sounds, similar to Naam; a single word; an entire hymn which can be put to music",
  },
  { text: "ਸਭ", meaning: "all, Everything" },
  { text: "ਸਦਾ", meaning: "Always" },
  { text: "ਸਾਧੇ", meaning: "arrange, control, achieve by some method" },
  { text: "ਸਗਲ", meaning: "all" },
  { text: "ਸਹਣਾ", meaning: "endure, suffer, support" },
  { text: "ਸਲਾਹ", meaning: "to praise" },
  { text: "ਸਮਾਈ", meaning: "absorbed in" },
  { text: "ਸਮਾਲੇ", meaning: "cherish, take care of, remember" },
  { text: "ਸਮਰਥ", meaning: "potent, capable, all powerful" },
  { text: "ਸੰਗਤਿ", meaning: "association, company, congregation" },
  { text: "ਸੰਗੀ", meaning: "companion" },
  { text: "ਸੰਗ", meaning: "with, close" },
  {
    text: "ਸੰਤ",
    meaning: "Saint, saintly person in tune with God, often used for Guru",
  },
  { text: "ਸਰਬ", meaning: "all" },
  {
    text: "ਸਰਨ",
    meaning: "shelter, protection, sanctuary; sanctify (var. sharan, sarnaaee)",
  },
  {
    text: "ਸਾਰੰਗ",
    meaning:
      "1. a musical melody, raag, pure with clarity; 2. peacock, crane, Indian cuckoo. 3. spotted deer 4. sword 5. elephant",
  },
  { text: "ਸਰੀਰ", meaning: "body, self" },
  { text: "ਸਰੀਰਾ", meaning: "body, wisdom" },
  { text: "ਸਉਦਾਗਰੀ", meaning: "trade, business" },
  { text: "ਸਵਾਰਿ", meaning: "to set right, decorate," },
  { text: "ਸੇਤੀ", meaning: "with, by, infuse, together" },
  {
    text: "ਸਹਿਜ",
    meaning:
      "state of peace and balance, tranquility, spontaneous, naturally - with the flow, in tune with the Infinite",
  },
  {
    text: "ਸੇਜ",
    meaning:
      "bed; divine bed representing union between God and the soul bride",
  },
  {
    text: "ਸੇਵਾ",
    meaning: "selfless-service, devotional service, volunteer effort",
  },
  { text: "ਸਿਆਣਪ", meaning: "cleverness, wisdom, intellect" },
  {
    text: "ਸਿਆਣਾ",
    meaning:
      "wise, clever, intellectual, knowledgeable, mature, cunning, crafty",
  },
  { text: "ਸਿਫਤਿ", meaning: "praise, glory" },
  { text: "ਸਿਲਕ", meaning: "rope (round neck), noose, thread" },
  {
    text: "ਸਿਮਰਿ",
    meaning: "remember with love, hold in your heart, meditate *see simran",
  },
  { text: "ਸਿੰਘ", meaning: "Lion" },
  { text: "ਸਿਸਟਿ", meaning: "creation, Creator, universe, world" },
  { text: "ਸਿਉ", meaning: "(pp) to, with (MP - noo)" },
  { text: "ਸੋਭਾ", meaning: "glory" },
  { text: "ਸੋਈ", meaning: "that one" },
  { text: "ਸੋਵਤ", meaning: "sleeping (sovana - to sleep)" },
  {
    text: "ਤੇਜ",
    meaning:
      "1. power, splendour, glory, victory  2. fire, passion, anger  3. speedy, swift, fast, sharp",
  },
  { text: "ਤਬ", meaning: "then" },
  {
    text: "ਤਾਪ",
    meaning: "1. heat, warmth, fever  2. affliction. 3. austerity",
  },
  {
    text: "ਤਰਾਈ",
    meaning:
      "1. floated, saved, floated across safely 2. Foot hill, low land, a marsh, meadow",
  },
  {
    text: "ਤਾਰੈ",
    meaning: "swim, be saved (tarnaa); taraana - to save, help to swim",
  },
  { text: "ਤਰੀਜੈ", meaning: "float it, get it across safely" },
  {
    text: "ਤੇ",
    meaning: "1. that  2. from, by, upon, by means of, on account of, 3. and",
  },
  { text: "ਤੇਰਾ", meaning: "your, yours" },
  { text: "ਤੇਤੇ", meaning: "that is, that's, they are" },
  {
    text: "ਤਿਸ",
    meaning: "1. from, which  2. He, she, it, that  3. Thirst, longing.",
  },
  { text: "ਥਾਪਿ", meaning: "establish, install, fix, engage" },
  {
    text: "ਠਾਢੇ",
    meaning: "1. stand, stands 2. cold, cool 3. quiet, tranquil",
  },
  { text: "ਥਾਪਿਆ", meaning: "impose, affect, effect" },
  { text: "ਠਉਰ", meaning: "Sanctuary, place of rest, support" },
  {
    text: "ਥੋਕ",
    meaning:
      "1. heap of anything like corn, material objects, anything. 2. wholesale",
  },
  {
    text: "ਤਿਆਗ",
    meaning:
      "abandon, give up, renounce, to give up maya; society, family, career etc.",
  },
  { text: "ਤਿਲਕ", meaning: "Coranation, coloured, mark on the forehead." },
  { text: "ਤੂਟੈ", meaning: "breaks, wiped out, broken" },
  {
    text: "ਉਦਾਸਾ",
    meaning: "without desire, detached, apart, dis-interested, neutral",
  },
  { text: "ਉਪਾੜੀ", meaning: "root out," },
  { text: "ਉਪਜੈ", meaning: "spring up, arise" },
  { text: "ਉਠਿ", meaning: "awake, arise, rise up, get up" },
  {
    text: "ਉਥਾਪਨਹਾਰਾ",
    meaning:
      "one who destroys, disestablishes, from ਉਥਾਪਨ s\xa0 uthaapan and the suffix ਹਾਰਾ s\xa0 haaraa one with the quality preceding; ਉਥਾਪਨ s\xa0 is itself from the the roots ਉ s\xa0 makes the opposite of the word following and ਥਾਪਨ s\xa0 which means establish",
  },
  {
    text: "ਉਤਰਿ",
    meaning:
      "1. descend, depart, come down, remove, drive out 2. North, opposite of which is ਦਖਣ s\xa0 dakhan South",
  },
  { text: "ਉਤਰਹਿ", meaning: "depart, remove, cross over," },
  { text: "ਵਾਜੇ", meaning: "rings, resound, play as of music" },
  { text: "ਵਡਿਆਈ", meaning: "greatness, glory, distinction" },
  { text: "ਵਡਭਾਗੀ", meaning: "fortunate" },
  { text: "ਵੈਰ", meaning: "enmity (var. bair); vairee or bairee - enemy" },
  { text: "ਵਣਿ", meaning: "in (within) forest/jungle/woods/trees" },
  { text: "ਵਰਣ", meaning: "n. color or caste; v. to desribe" },
  { text: "ਵਰਖੈ", meaning: "rains, pours" },
  { text: "ਵਸਾਇਆ", meaning: "to live, abide, be enshrined (vasnaa)" },
  { text: "ਵਸੈ", meaning: "live, abide" },
  { text: "ਵਸਿਆ", meaning: "dwells" },
  {
    text: "ਵਿਡਾਣੀ",
    meaning: "Unfamiliar, Wonderful marvellous, astonishing, other or another",
  },
  { text: "ਵਿਜੋਗਾ", meaning: "separation, disunion, loss, bereavement" },
  { text: "ਵਿਕਾਰ", meaning: "sins, evil" },
  { text: "ਵਿਸਾਰ", meaning: "forget; MP - bhulnaa" },
  { text: "ਮੈਨੂੰ", meaning: "I" },
  { text: '"ਸੀ', meaning: ",was" },
  { text: "ਲਈ", meaning: "for" },
  { text: "‘ਤੇ", meaning: "on" },
  { text: "ਹਨ", meaning: "are" },
  { text: "ਉਹ", meaning: "they" },
  { text: "ਹੋ", meaning: "be" },
  { text: "‘ਤੇ", meaning: "at" },
  { text: "ਇੱਕ", meaning: "one" },
  { text: "ਹੈ", meaning: "have" },
  { text: "ਤੱਕ", meaning: "from" },
  { text: "ਕੇ", meaning: "by" },
  { text: "ਗਰਮ", meaning: "hot" },
  { text: "ਪਰ", meaning: "but" },
  { text: "ਹੈ", meaning: "is" },
  { text: "ਤੁਹਾਨੂੰ", meaning: "you" },
  { text: "ਜ", meaning: "or" },
  { text: '"ਸੀ', meaning: ",had" },
  { text: "The", meaning: "the" },
  { text: "ਦੇ", meaning: "of" },
  { text: "ਨੂੰ", meaning: "to" },
  { text: "ਇੱਕ", meaning: "a" },
  { text: "ਵਿੱਚ", meaning: "in" },
  { text: "ਸਾਨੂੰ", meaning: "we" },
  { text: "ਬਾਹਰ", meaning: "out" },
  { text: "ਸਨ", meaning: "were" },
  { text: "ਕਰਦੇ", meaning: "do" },
  { text: "ਆਪਣੇ", meaning: "their" },
  { text: "ਵਾਰ", meaning: "time" },
  { text: "ਜੇ", meaning: "if" },
  { text: "ਕਰੇਗਾ", meaning: "will" },
  { text: "ਕਿੰਨੇ", meaning: "how" },
  { text: "ਇੱਕ", meaning: "an" },
  { text: "ਤਿੰਨ", meaning: "three" },
  { text: "ਚਾਹੁੰਦੇ", meaning: "want" },
  { text: "ਹਵਾ", meaning: "air" },
  { text: "ਖੇਡਣ", meaning: "play" },
  { text: "ਪਾ", meaning: "put" },
  { text: "ਵੱਡੇ", meaning: "large" },
  { text: "ਜੋੜ", meaning: "spell" },
  { text: "ਸ਼ਾਮਿਲ", meaning: "add" },
  { text: "ਵੀ", meaning: "even" },
  { text: "ਇਥੇ", meaning: "here" },
  { text: "ਵੱਡੇ", meaning: "big" },
  { text: "ਉੱਚ", meaning: "high" },
  { text: "ਅਜਿਹੇ", meaning: "such" },
  { text: "ਕੰਮ", meaning: "act" },
  { text: "ਇਸੇ", meaning: "why" },
  { text: "ਪੁੱਛੋ", meaning: "ask" },
  { text: "ਲੋਕ", meaning: "men" },
  { text: "ਤਬਦੀਲੀ", meaning: "change" },
  { text: "ਹਲਕਾ", meaning: "light" },
  { text: "ਦਿਆਲੂ", meaning: "kind" },
  { text: "ਬੰਦ", meaning: "off" },
  { text: "ਤਸਵੀਰ", meaning: "picture" },
  { text: "ਜਾਨਵਰ", meaning: "animal" },
  { text: "ਬਿੰਦੂ", meaning: "point" },
  { text: "ਮਾਤਾ", meaning: "mother" },
  { text: "ਸਵੈ", meaning: "self" },
  { text: "ਨਵ", meaning: "new" },
  { text: "ਲੈ", meaning: "take" },
  { text: "ਪ੍ਰਾਪਤ", meaning: "get" },
  { text: "ਸਥਾਨ", meaning: "place" },
  { text: "ਰਹਿੰਦੇ", meaning: "live" },
  { text: "ਵਾਪਸ", meaning: "back" },
  { text: "ਥੋੜਾ", meaning: "little" },
  { text: "ਸਿਰਫ", meaning: "only" },
  { text: "ਦੌਰ", meaning: "round" },
  { text: "ਪ੍ਰਦਰਸ਼ਨ", meaning: "show" },
  { text: "ਚੰਗਾ", meaning: "good" },
  { text: "ਮੈਨੂੰ", meaning: "me" },
  { text: "ਦੇਣ", meaning: "give" },
  { text: "ਸਾਡੇ", meaning: "our" },
  { text: "ਹੇਠ", meaning: "under" },
  { text: "ਨਾਮ", meaning: "name" },
  { text: "ਦੁਆਰਾ", meaning: "through" },
  { text: "ਮਹਾਨ", meaning: "great" },
  { text: "ਸੋਚਦੇ", meaning: "think" },
  { text: "ਖੋਜੋ", meaning: "low" },
  { text: "ਲਾਈਨ", meaning: "line" },
  { text: "ਵਾਰੀ", meaning: "turn" },
  { text: "ਕਾਰਨ", meaning: "cause" },
  { text: "ਅੱਗੇ", meaning: "before" },
  { text: "ਮੂਵ", meaning: "move" },
  { text: "ਪੁਰਾਣੀ", meaning: "old" },
  { text: "ਸਾਰੇ", meaning: "all" },
  { text: "ਉੱਥੇ", meaning: "there" },
  { text: "ਜਦ", meaning: "when" },
  { text: "ਅਪ", meaning: "up" },
  { text: "ਵਰਤਣ", meaning: "use" },
  { text: "ਤੁਹਾਡੇ", meaning: "your" },
  { text: "ਬਾਰੇ", meaning: "about" },
  { text: "ਫਿਰ", meaning: "then" },
  { text: "ਨੂੰ", meaning: "them" },
  { text: "ਸੀ", meaning: "would" },
  { text: "ਵਰਗੇ", meaning: "like" },
  { text: "ਇਹ", meaning: "these" },
  { text: "ਲੰਬੇ", meaning: "long" },
  { text: "ਕਰ", meaning: "make" },
  { text: '"ਵੇਖੋ', meaning: ",see" },
  { text: "ਹੈ", meaning: "has" },
  { text: "ਦੇਖ", meaning: "look" },
  { text: "ਹੋਰ", meaning: "more" },
  { text: "ਜਾਣ", meaning: "go" },
  { text: "ਆ", meaning: "come" },
  { text: "ਆਵਾਜ਼", meaning: "sound" },
  { text: "ਸਭ", meaning: "most" },
  { text: "ਲੋਕ", meaning: "people" },
  { text: "ਮੇਰੇ", meaning: "my" },
  { text: "ਵੱਧ", meaning: "over" },
  { text: "ਵੱਧ", meaning: "than" },
  { text: "ਪਹਿਲੀ", meaning: "first" },
  { text: "ਜੋ", meaning: "who" },
  { text: "ਡਾਊਨ", meaning: "down" },
  { text: "ਪਾਸੇ", meaning: "side" },
  { text: "ਖੜ੍ਹੇ", meaning: "stand" },
  { text: "ਸਫ਼ਾ", meaning: "page" },
  { text: "ਪਾਇਆ", meaning: "found" },
  { text: "ਵਾਧਾ", meaning: "grow" },
  { text: "ਸਿੱਖਣ", meaning: "learn" },
  { text: "ਬੂਟਾ", meaning: "plant" },
  { text: "ਭੋਜਨ", meaning: "food" },
  { text: "ਰੱਖਣ", meaning: "keep" },
  { text: "ਅੱਖ", meaning: "eye" },
  { text: "ਪਿਛਲੇ", meaning: "last" },
  { text: "ਦਿਉ", meaning: "let" },
  { text: "ਸੋਚਿਆ", meaning: "thought" },
  { text: "ਪਾਰ", meaning: "cross" },
  { text: "ਹਾਰਡ", meaning: "hard" },
  { text: "ਸ਼ਾਇਦ", meaning: "might" },
  { text: "ਕਹਾਣੀ", meaning: "story" },
  { text: "ਆਰਾ", meaning: "saw" },
  { text: "ਦੂਰ", meaning: "far" },
  { text: "ਖਿੱਚਣ", meaning: "draw" },
  { text: "ਦੇਰ", meaning: "late" },
  { text: "ਰਨ", meaning: "run" },
  { text: "ਜਦਕਿ", meaning: "while" },
  { text: "ਪ੍ਰੈੱਸ", meaning: "press" },
  { text: "ਕੁਝ", meaning: "few" },
  { text: "ਉੱਤਰ", meaning: "north" },
  { text: "ਲੈ", meaning: "carry" },
  { text: "ਕਮਰੇ", meaning: "room" },
  { text: "ਦੋਸਤ", meaning: "friend" },
  { text: "ਮੱਛੀ", meaning: "fish" },
  { text: "ਪਹਾੜ", meaning: "mountain" },
  { text: "ਰੂਕੋ", meaning: "stop" },
  { text: "ਅਧਾਰ", meaning: "base" },
  { text: "ਸੁਣਦੇ", meaning: "hear" },
  { text: "ਘੋੜਾ", meaning: "horse" },
  { text: "ਕੱਟ", meaning: "cut" },
  { text: "ਜਾਗ", meaning: "watch" },
  { text: "ਮੁੱਖ", meaning: "main" },
  { text: "ਖੁੱਲ੍ਹਾ", meaning: "open" },
  { text: '"ਚਿੱਟੇ', meaning: ",white" },
  { text: "ਬੱਚੇ", meaning: "children" },
  { text: "ਸ਼ੁਰੂ", meaning: "begin" },
  { text: "ਮਿਲੀ", meaning: "got" },
  { text: "ਤੁਰ", meaning: "walk" },
  { text: "ਉਦਾਹਰਨ", meaning: "example" },
  { text: "ਸੌਖਾ", meaning: "ease" },
  { text: "ਪੇਪਰ", meaning: "paper" },
  { text: "ਜਿਹੜੇ", meaning: "those" },
  { text: "ਦੋਨੋ", meaning: "both" },
  { text: "ਨਿਸ਼ਾਨ", meaning: "mark" },
  { text: "ਅਕਸਰ", meaning: "often" },
  { text: "ਮੀਲ", meaning: "mile" },
  { text: "ਨਦੀ", meaning: "river" },
  { text: "ਪੈਰ", meaning: "feet" },
  { text: "ਕਾਫ਼ੀ", meaning: "enough" },
  { text: "ਸਮਤਲ", meaning: "plain" },
  { text: "ਆਮ", meaning: "usual" },
  { text: "ਨੌਜਵਾਨ", meaning: "young" },
  { text: "ਤਿਆਰ", meaning: "ready" },
  { text: "ਉਪਰੋਕਤ", meaning: "above" },
  { text: "ਕਦੇ", meaning: "ever" },
  { text: "ਲਾਲ", meaning: "red" },
  { text: "ਪਰ", meaning: "though" },
  { text: "ਪੰਛੀ", meaning: "bird" },
  { text: "ਕੁੱਤੇ", meaning: "dog" },
  { text: "ਸਿੱਧੀ", meaning: "direct" },
  { text: "ਪੈਦਾ", meaning: "pose" },
  { text: "ਗੀਤ", meaning: "song" },
  { text: "ਮਾਪ", meaning: "measure" },
  { text: "ਉਤਪਾਦ", meaning: "product" },
  { text: "ਕਾਲਾ", meaning: "black" },
  { text: "ਛੋਟਾ", meaning: "short" },
  { text: "ਅੰਕ", meaning: "numeral" },
  { text: "ਹਵਾ", meaning: "wind" },
  { text: "ਜਹਾਜ਼", meaning: "ship" },
  { text: "ਅੱਧੇ", meaning: "half" },
  { text: "ਚੱਟਾਨ", meaning: "rock" },
  { text: "ਕ੍ਰਮ", meaning: "order" },
  { text: "ਦੱਖਣ", meaning: "south" },
  { text: "ਟੁਕੜੇ", meaning: "piece" },
  { text: "ਪਾਸ", meaning: "pass" },
  { text: "ਸਾਰੀ", meaning: "whole" },
  { text: "ਇੰਚ", meaning: "inch" },
  { text: "ਗੁਣਾ", meaning: "multiply" },
  { text: "ਰਹਿਣ", meaning: "stay" },
  { text: "ਚੱਕਰ", meaning: "wheel" },
  { text: "ਪੂਰੇ", meaning: "full" },
  { text: "ਫੋਰਸ", meaning: "force" },
  { text: "ਨੀਲਾ", meaning: "blue" },
  { text: "ਇਕਾਈ", meaning: "object" },
  { text: "ਸਤਹ", meaning: "surface" },
  { text: "ਡੂੰਘੇ", meaning: "deep" },
  { text: "ਚੰਦ", meaning: "moon" },
  { text: "ਪੈਰ", meaning: "foot" },
  { text: "ਵਿਅਸਤ", meaning: "busy" },
  { text: "ਕਿਸ਼ਤੀ", meaning: "boat" },
  { text: "ਆਮ", meaning: "common" },
  { text: "ਜਹਾਜ਼", meaning: "plane" },
  { text: "ਬੈਠ", meaning: "stead" },
  { text: "ਖੁਸ਼ਕ", meaning: "dry" },
  { text: "ਹੈਰਾਨ", meaning: "wonder" },
  { text: "ਹੱਸ", meaning: "laugh" },
  { text: "ਹਜ਼ਾਰ", meaning: "thousand" },
  { text: "ਸਾਲ", meaning: "ago" },
  { text: "ਭੱਜ", meaning: "ran" },
  { text: "ਸ਼ਕਲ", meaning: "shape" },
  { text: "ਜ਼ਿੱਲਤ", meaning: "equate" },
  { text: "ਗਰਮ", meaning: "hot" },
  { text: "ਮਿਸ", meaning: "miss" },
  { text: "ਟਾਇਰ", meaning: "tire" },
  { text: "ਲਿਆਉਣ", meaning: "bring" },
  { text: "ਜੀ", meaning: "yes" },
  { text: "ਦੂਰ", meaning: "distant" },
  { text: "ਪੂਰਬ", meaning: "east" },
  { text: "ਚਿੱਤਰਕਾਰੀ", meaning: "paint" },
  { text: "ਕਸਬੇ", meaning: "town" },
  { text: "ਜੁਰਮਾਨਾ", meaning: "fine" },
  { text: "ਉੱਡਦੀ", meaning: "fly" },
  { text: "ਡਿੱਗ", meaning: "fall" },
  { text: "ਪੁਕਾਰ", meaning: "cry" },
  { text: "ਹਨੇਰੇ", meaning: "dark" },
  { text: "ਨੋਟ", meaning: "note" },
  { text: "ਸਿਤਾਰਾ", meaning: "star" },
  { text: "ਨਾਮ", meaning: "noun" },
  { text: "ਖੇਤਰ", meaning: "field" },
  { text: "ਯੋਗ", meaning: "able" },
  { text: "ਸੇਰ", meaning: "pound" },
  { text: "ਸਮਾਪਤ", meaning: "done" },
  { text: "ਸੁੰਦਰਤਾ", meaning: "beauty" },
  { text: "ਸਾਹਮਣੇ", meaning: "front" },
  { text: "ਫਾਈਨਲ", meaning: "final" },
  { text: "ਹਰੇ", meaning: "green" },
  { text: "ਓਹੁ", meaning: "oh" },
  { text: "ਤੇਜ਼", meaning: "quick" },
  { text: "ਸਮੁੰਦਰ", meaning: "ocean" },
  { text: "ਨਿੱਘਾ", meaning: "warm" },
  { text: "ਮੁਫ਼ਤ", meaning: "free" },
  { text: "ਮਿੰਟ", meaning: "minute" },
  { text: "ਮਜ਼ਬੂਤ", meaning: "strong" },
  { text: "ਵਿਸ਼ੇਸ਼", meaning: "special" },
  { text: "ਮਨ", meaning: "mind" },
  { text: "ਪਿੱਛੇ", meaning: "behind" },
  { text: "ਪੂਛ", meaning: "tail" },
  { text: "ਉਤਪਾਦਨ", meaning: "produce" },
  { text: "ਸਪੇਸ", meaning: "space" },
  { text: "ਸੁਣਿਆ", meaning: "heard" },
  { text: "ਵਧੀਆ", meaning: "best" },
  { text: "ਘੰਟੇ", meaning: "hour" },
  { text: "ਬਿਹਤਰ", meaning: "better" },
  { text: "ਸੌ", meaning: "hundred" },
  { text: "ਪੰਜ", meaning: "five" },
  { text: "ਪੱਛਮ", meaning: "west" },
  { text: "ਜ਼ਮੀਨ", meaning: "ground" },
  { text: "ਵਿਆਜ", meaning: "interest" },
  { text: "ਫਾਸਟ", meaning: "fast" },
  { text: "ਕ੍ਰਿਆ", meaning: "verb" },
  { text: "ਛੇ", meaning: "six" },
  { text: "ਯਾਤਰਾ", meaning: "travel" },
  { text: "ਘੱਟ", meaning: "less" },
  { text: "ਦਸ", meaning: "ten" },
  { text: "ਸਧਾਰਨ", meaning: "simple" },
  { text: "ਸ੍ਵਰ", meaning: "vowel" },
  { text: "ਵੱਲ", meaning: "toward" },
  { text: "ਰੱਖਣਗੇ", meaning: "lay" },
  { text: "ਪੈਟਰਨ", meaning: "pattern" },
  { text: "ਹੌਲੀ", meaning: "slow" },
  { text: "ਕਦਰ", meaning: "center" },
  { text: "ਵਿਖਾਈ", meaning: "appear" },
  { text: '"ਨਕਸ਼ਾ', meaning: ",map" },
  { text: "ਰਾਜ", meaning: "govern" },
  { text: "ਖਿੱਚੋ", meaning: "pull" },
  { text: "ਠੰਡੇ", meaning: "cold" },
  { text: "ਊਰਜਾ", meaning: "energy" },
  { text: "ਸ਼ਿਕਾਰ", meaning: "hunt" },
  { text: "ਸੰਭਵ", meaning: "probable" },
  { text: "ਮੰਜੇ", meaning: "bed" },
  { text: "ਅੰਡੇ", meaning: "egg" },
  { text: "ਸਫ਼ਰ", meaning: "ride" },
  { text: "ਸੈੱਲ", meaning: "cell" },
  { text: "ਸ਼ਾਇਦ", meaning: "perhaps" },
  { text: "ਚੁੱਕਣ", meaning: "pick" },
  { text: "ਅਚਾਨਕ", meaning: "sudden" },
  { text: "ਗਿਣੋ", meaning: "count" },
  { text: "ਵਰਗ", meaning: "square" },
  { text: "ਲੰਬਾਈ", meaning: "length" },
  { text: "ਕਲਾ", meaning: "art" },
  { text: "ਵਿਸ਼ੇ", meaning: "subject" },
  { text: "ਵਸਣ", meaning: "settle" },
  { text: "ਆਈਸ", meaning: "ice" },
  { text: "ਚੱਕਰ", meaning: "circle" },
  { text: "ਜੋੜਾ", meaning: "pair" },
  { text: "ਪਾੜਾ", meaning: "divide" },
  { text: "ਿਸਹਾਰੀ", meaning: "syllable" },
  { text: "ਸ਼ਾਨਦਾਰ", meaning: "grand" },
  { text: "ਬਾਲ", meaning: "ball" },
  { text: "ਲਹਿਰ", meaning: "wave" },
  { text: "ਡ੍ਰੌਪ", meaning: "drop" },
  { text: "am", meaning: "am" },
  { text: "ਮੌਜੂਦ", meaning: "present" },
  { text: "ਭਾਰੀ", meaning: "heavy" },
  { text: "ਨਾਚ", meaning: "dance" },
  { text: "ਸਥਿਤੀ", meaning: "position" },
  { text: "ਆਰਮ", meaning: "arm" },
  { text: "ਚੌੜਾ", meaning: "wide" },
  { text: "ਜਹਾਜ਼", meaning: "sail" },
  { text: "ਸਮੱਗਰੀ", meaning: "material" },
  { text: '"ਬਾਗ', meaning: ",fraction" },
  { text: "ਜੰਗਲ", meaning: "forest" },
  { text: "ਬੈਠ", meaning: "sit" },
  { text: "ਸਟੋਰ", meaning: "store" },
  { text: "ਸਾਬਤ", meaning: "prove" },
  { text: "ਇਕੋ", meaning: "lone" },
  { text: "ਲੱਤ", meaning: "leg" },
  { text: "ਕਸਰਤ", meaning: "exercise" },
  { text: "ਕੰਧ", meaning: "wall" },
  { text: "ਕੈਚ", meaning: "catch" },
  { text: "ਮਾਊਟ", meaning: "mount" },
  { text: "ਅਸਮਾਨ", meaning: "sky" },
  { text: "ਬੋਰਡ", meaning: "board" },
  { text: "ਸਰਦੀ", meaning: "winter" },
  { text: "ਲਿਖਿਆ", meaning: "written" },
  { text: "ਜੰਗਲੀ", meaning: "wild" },
  { text: "ਸਾਧਨ", meaning: "instrument" },
  { text: "ਰੱਖਿਆ", meaning: "kept" },
  { text: "ਗਲਾਸ", meaning: "glass" },
  { text: "ਘਾਹ", meaning: "grass" },
  { text: "ਗਊ", meaning: "cow" },
  { text: "ਕਿਨਾਰੇ", meaning: "edge" },
  { text: "ਪਿਛਲੇ", meaning: "past" },
  { text: "ਸਾਫਟ", meaning: "soft" },
  { text: "ਮਜ਼ੇਦਾਰ", meaning: "fun" },
  { text: "ਚਮਕਦਾਰ", meaning: "bright" },
  { text: "ਗੈਸ", meaning: "gas" },
  { text: "ਲੱਖ", meaning: "million" },
  { text: "ਰੱਖਣਾ", meaning: "bear" },
  { text: "ਖੁਸ਼", meaning: "happy" },
  { text: "ਫੁੱਲ", meaning: "flower" },
  { text: "ਸਜਾਵੇਗਾ", meaning: "clothe" },
  { text: "ਅਜੀਬ", meaning: "strange" },
  { text: "ਚੁੱਕਾ", meaning: "gone" },
  { text: "ਵਪਾਰ", meaning: "trade" },
  { text: "ਭਜਨ", meaning: "melody" },
  { text: "ਪ੍ਰਾਪਤ", meaning: "receive" },
  { text: "ਕਤਾਰ", meaning: "row" },
  { text: "ਸਹੀ", meaning: "exact" },
  { text: "ਪ੍ਰਤੀਕ", meaning: "symbol" },
  { text: "ਮਰ", meaning: "die" },
  { text: "ਘੱਟ", meaning: "least" },
  { text: "ਦੇਵੇਤੇ", meaning: "shout" },
  { text: "ਬੀਜ", meaning: "seed" },
  { text: "ਟੋਨ", meaning: "tone" },
  { text: "ਸੁਝਾਅ", meaning: "suggest" },
  { text: "ਬ੍ਰੇਕ", meaning: "break" },
  { text: "ਔਰਤ", meaning: "lady" },
  { text: "ਯਾਰਡ", meaning: "yard" },
  { text: "ਵਧ", meaning: "rise" },
  { text: "ਬੁਰਾ", meaning: "bad" },
  { text: "ਉੱਡਿਆ", meaning: "blow" },
  { text: "ਫੀਸਦੀ", meaning: "cent" },
  { text: "ਮਿਕਸ", meaning: "mix" },
  { text: "ਤਾਰ", meaning: "wire" },
  { text: "ਲਾਗਤ", meaning: "cost" },
  { text: "ਭੂਰਾ", meaning: "brown" },
  { text: "ਪਹਿਨਣ", meaning: "wear" },
  { text: "ਬਾਗ", meaning: "garden" },
  { text: "ਬਰਾਬਰ", meaning: "equal" },
  { text: "ਡਿੱਗ", meaning: "fell" },
  { text: "ਫਿੱਟ", meaning: "fit" },
  { text: "ਵਹਿਣਾ", meaning: "flow" },
  { text: "ਮੇਲਾ", meaning: "fair" },
  { text: "ਬਕ", meaning: "bank" },
  { text: "ਦਸ਼ਮਲਵ", meaning: "decimal" },
  { text: "ਕੰਨ", meaning: "ear" },
  { text: "ਕਾਫ਼ੀ", meaning: "quite" },
  { text: "ਤੋੜ", meaning: "broke" },
  { text: "ਮੱਧ", meaning: "middle" },
  { text: "ਝੀਲ", meaning: "lake" },
  { text: "ਪਲ", meaning: "moment" },
  { text: "ਪੈਮਾਨੇ", meaning: "scale" },
  { text: "ਉੱਚੀ", meaning: "loud" },
  { text: "ਬਸੰਤ", meaning: "spring" },
  { text: "ਸਿੱਧਾ", meaning: "straight" },
  { text: "ਕੋਸ਼", meaning: "dictionary" },
  { text: "ਦੁੱਧ", meaning: "milk" },
  { text: "ਅੰਗ", meaning: "organ" },
  { text: "ਅਨੁਭਾਗ", meaning: "section" },
  { text: "ਪਹਿਰਾਵਾ", meaning: "dress" },
  { text: "ਹੈਰਾਨੀ", meaning: "surprise" },
  { text: "ਚੁੱਪ", meaning: "quiet" },
  { text: "ਛੋਟੇ", meaning: "tiny" },
  { text: "ਚੜ੍ਹਨਾ", meaning: "climb" },
  { text: "ਠੰਡਾ", meaning: "cool" },
  { text: "ਡਿਜ਼ਾਇਨ", meaning: "design" },
  { text: "ਗਰੀਬ", meaning: "poor" },
  { text: "ਤਜਰਬੇ", meaning: "experiment" },
  { text: "ਤਲ", meaning: "bottom" },
  { text: "ਲੋਹੇ", meaning: "iron" },
  { text: "ਇੱਕਲੇ", meaning: "single" },
  { text: "ਸਟਿੱਕ", meaning: "stick" },
  { text: "ਫਲੈਟ", meaning: "flat" },
  { text: "ਵੀਹ", meaning: "twenty" },
  { text: "ਮੁਸਕਾਨ", meaning: "smile" },
  { text: "ਕ੍ਰੀਜ਼", meaning: "crease" },
  { text: "ਮੋਰੀ", meaning: "hole" },
  { text: "ਛਾਲ", meaning: "jump" },
  { text: "ਅੱਠ", meaning: "eight" },
  { text: "ਰੂਟ", meaning: "root" },
  { text: "ਖਰੀਦਣ", meaning: "buy" },
  { text: "ਚੁੱਕਣ", meaning: "raise" },
  { text: "ਮੈਟਲ", meaning: "metal" },
  { text: "ਕੀ", meaning: "whether" },
  { text: "ਧੱਕਾ", meaning: "push" },
  { text: "ਸੱਤ", meaning: "seven" },
  { text: "ਪੈਰਾ", meaning: "paragraph" },
  { text: '"ਤੀਜਾ', meaning: ",third" },
  { text: "ਦੇਣਗੇ", meaning: "shall" },
  { text: "ਚਾਰ", meaning: "held" },
  { text: "ਵਾਲ", meaning: "hair" },
  { text: "ਕੁੱਕ", meaning: "cook" },
  { text: "ਮੰਜ਼ਿਲ", meaning: "floor" },
  { text: "ਕੋਈ", meaning: "either" },
  { text: "ਨਤੀਜਾ", meaning: "result" },
  { text: "ਪਹਾੜੀ", meaning: "hill" },
  { text: "ਸੁਰੱਖਿਅਤ", meaning: "safe" },
  { text: "ਬਿੱਲੀ", meaning: "cat" },
  { text: "ਸਦੀ", meaning: "century" },
  { text: "ਬਿੱਟ", meaning: "bit" },
  { text: "ਤਟ", meaning: "coast" },
  { text: "ਕਾਪੀ", meaning: "copy" },
  { text: "ਵਾਕੰਸ਼", meaning: "phrase" },
  { text: "ਚੁੱਪ", meaning: "silent" },
  { text: "ਲੰਬਾ", meaning: "tall" },
  { text: "ਰੇਤ", meaning: "sand" },
  { text: "ਮਿੱਟੀ", meaning: "soil" },
  { text: "ਰੋਲ", meaning: "roll" },
  { text: "ਫਿੰਗਰ", meaning: "finger" },
  { text: "ਲੜਾਈ", meaning: "fight" },
  { text: "ਝੂਠ", meaning: "lie" },
  { text: "ਹਰਾਇਆ", meaning: "beat" },
  { text: "ਉਤਸਾਹਿਤ", meaning: "excite" },
  { text: "ਕੁਦਰਤੀ", meaning: "natural" },
  { text: "ਝਲਕ", meaning: "view" },
  { text: "ਭਾਵਨਾ", meaning: "sense" },
  { text: "ਕੁਰਸੀ", meaning: "chair" },
  { text: "ਖ਼ਤਰਾ", meaning: "danger" },
  { text: "ਅਮੀਰ", meaning: "rich" },
  { text: "ਮੋਟੀ", meaning: "thick" },
  { text: "ਸਿਪਾਹੀ", meaning: "soldier" },
  { text: "ਅਭਿਆਸ", meaning: "practice" },
  { text: "ਵੱਖਰੇ", meaning: "separate" },
  { text: "ਕ੍ਰਿਪਾ", meaning: "please" },
  { text: "ਦੁਪਹਿਰ", meaning: "noon" },
  { text: "ਆਧੁਨਿਕ", meaning: "modern" },
  { text: "ਤੱਤ", meaning: "element" },
  { text: "ਹਿੱਟ", meaning: "hit" },
  { text: "ਕੋਨੇ", meaning: "corner" },
  { text: "ਲੱਭਣ", meaning: "locate" },
  { text: "ਰਿੰਗ", meaning: "ring" },
  { text: "ਕੀੜੇ", meaning: "insect" },
  { text: "ਫੜਿਆ", meaning: "caught" },
  { text: "ਰੇਡੀਓ", meaning: "radio" },
  { text: "ਗੱਲ", meaning: "spoke" },
  { text: "ਐਟਮ", meaning: "atom" },
  { text: "ਮਨੁੱਖੀ", meaning: "human" },
  { text: "ਹੱਡੀ", meaning: "bone" },
  { text: "ਰੇਲ", meaning: "rail" },
  { text: "ਮੁਹੱਈਆ", meaning: "provide" },
  { text: "ਸਹਿਮਤ", meaning: "agree" },
  { text: "ਕੋਮਲ", meaning: "gentle" },
  { text: "ਕਪਤਾਨ", meaning: "captain" },
  { text: "guess", meaning: "guess" },
  { text: "ਤਿੱਖੀ", meaning: "sharp" },
  { text: "ਵਿੰਗ", meaning: "wing" },
  { text: "ਨੇੜਲਾ", meaning: "neighbor" },
  { text: "ਧੋਣ", meaning: "wash" },
  { text: "ਬੱਲੇਬਾਜ਼ੀ", meaning: "bat" },
  { text: "ਭੀੜ", meaning: "crowd" },
  { text: "ਮਕਈ", meaning: "corn" },
  { text: "ਕਵਿਤਾ", meaning: "poem" },
  { text: "ਸਤਰ", meaning: "string" },
  { text: "ਘੰਟੀ", meaning: "bell" },
  { text: "ਨਿਰਭਰ", meaning: "depend" },
  { text: "ਮੀਟ", meaning: "meat" },
  { text: "ਟਿਊਬ", meaning: "tube" },
  { text: "ਮਸ਼ਹੂਰ", meaning: "famous" },
  { text: "ਸਟਰੀਮ", meaning: "stream" },
  { text: "ਨਜ਼ਰ", meaning: "sight" },
  { text: "ਪਤਲੇ", meaning: "thin" },
  { text: "ਤਿਕੋਣ", meaning: "triangle" },
  { text: "ਗ੍ਰਹਿ", meaning: "planet" },
  { text: "ਬਸਤੀ", meaning: "colony" },
  { text: "ਟਾਈ", meaning: "tie" },
  { text: '"ਦਿਓ', meaning: ",enter" },
  { text: "ਮੁੱਖ", meaning: "major" },
  { text: "ਤਾਜ਼ਾ", meaning: "fresh" },
  { text: "ਭੇਜਣ", meaning: "send" },
  { text: "ਪੀਲੇ", meaning: "yellow" },
  { text: "ਬੰਦੂਕ", meaning: "gun" },
  { text: "ਪ੍ਰਿੰਟ", meaning: "print" },
  { text: "ਮਰੇ", meaning: "dead" },
  { text: "ਸਪਾਟ", meaning: "spot" },
  { text: "ਮਾਰੂਥਲ", meaning: "desert" },
  { text: "ਮੁਕੱਦਮੇ", meaning: "suit" },
  { text: "ਮੌਜੂਦਾ", meaning: "current" },
  { text: "ਲਿਫਟ", meaning: "lift" },
  { text: "ਉੱਠਿਆ", meaning: "rose" },
  { text: "ਪਹੁੰਚਦੇ", meaning: "arrive" },
  { text: "ਮਾਸਟਰ", meaning: "master" },
  { text: "ਟਰੈਕ", meaning: "track" },
  { text: "ਮਾਤਾ", meaning: "parent" },
  { text: "ਕੰਢੇ", meaning: "shore" },
  { text: "ਵੰਡ", meaning: "division" },
  { text: "ਸ਼ੀਟ", meaning: "sheet" },
  { text: "ਪਦਾਰਥ", meaning: "substance" },
  { text: "ਪੋਸਟ", meaning: "post" },
  { text: "ਖਰਚ", meaning: "spend" },
  { text: "ਕੋਰਿਜ਼", meaning: "chord" },
  { text: "ਚਰਬੀ", meaning: "fat" },
  { text: "ਖੁਸ਼", meaning: "glad" },
  { text: "ਅਸਲੀ", meaning: "original" },
  { text: "ਸ਼ੇਅਰ", meaning: "share" },
  { text: "ਸਟੇਸ਼ਨ", meaning: "station" },
  { text: "ਡੈਡੀ", meaning: "dad" },
  { text: "ਚਾਰਜ", meaning: "charge" },
  { text: "ਸਹੀ", meaning: "proper" },
  { text: "ਸਿਗਮਿੰਟ", meaning: "segment" },
  { text: "ਬਤਖ਼", meaning: "duck" },
  { text: "ਤੁਰੰਤ", meaning: "instant" },
  { text: "ਤਿਆਰ", meaning: "populate" },
  { text: "ਮਟਰੀ", meaning: "chick" },
  { text: "ਪਿਆਰੇ", meaning: "dear" },
  { text: "ਦੁਸ਼ਮਣ", meaning: "enemy" },
  { text: "ਜਵਾਬ", meaning: "reply" },
  { text: "ਆ", meaning: "occur" },
  { text: "ਭਾਫ਼", meaning: "steam" },
  { text: "ਮੋਸ਼ਨ", meaning: "motion" },
  { text: "ਤਰਲ", meaning: "liquid" },
  { text: "ਸਮਰੱਥਾ", meaning: "quotient" },
  { text: "ਦੰਦ", meaning: "teeth" },
  { text: "ਸ਼ੈੱਲ", meaning: "shell" },
  { text: "ਗਰਦਨ", meaning: "neck" },
  { text: "ਆਕਸੀਜਨ", meaning: "oxygen" },
  { text: "ਖੰਡ", meaning: "sugar" },
  { text: "ਪਰੈਟੀ", meaning: "pretty" },
  { text: "ਹੁਨਰ", meaning: "skill" },
  { text: "ਮਹਿਲਾ", meaning: "women" },
  { text: "ਸੀਜ਼ਨ", meaning: "season" },
  { text: "ਚੁੰਬਕ", meaning: "magnet" },
  { text: "ਸਿਲਵਰ", meaning: "silver" },
  { text: "ਧੰਨਵਾਦ", meaning: "thank" },
  { text: "ਸ਼ਾਖਾ", meaning: "branch" },
  { text: "ਮੈਚ", meaning: "match" },
  { text: "ਪਿਛੇਤਰ", meaning: "suffix" },
  { text: "ਅੰਜੀਰ", meaning: "fig" },
  { text: "ਡਰ", meaning: "afraid" },
  { text: "ਵੱਡੇ", meaning: "huge" },
  { text: "ਸਟੀਲ", meaning: "steel" },
  { text: "ਅੱਗੇ", meaning: "forward" },
  { text: "ਇਸੇ", meaning: "similar" },
  { text: "ਸਕੋਰ", meaning: "score" },
  { text: "ਸੇਬ", meaning: "apple" },
  { text: "ਖਰੀਦੀ", meaning: "bought" },
  { text: "ਪਿੱਚ", meaning: "pitch" },
  { text: "ਕੋਟ", meaning: "coat" },
  { text: "ਜਨਤਕ", meaning: "mass" },
  { text: "ਕਾਰਡ", meaning: "card" },
  { text: "ਪਹਿਰੇਦਾਰ", meaning: "band" },
  { text: "ਰੱਸੀ", meaning: "rope" },
  { text: "ਸਿਲੱਪ", meaning: "slip" },
  { text: "ਜਿੱਤ", meaning: "win" },
  { text: "ਸੁਪਨੇ", meaning: "dream" },
  { text: "ਹਾਲਤ", meaning: "condition" },
  { text: "ਕੁੱਲ", meaning: "total" },
  { text: "ਬੁਨਿਆਦੀ", meaning: "basic" },
  { text: "ਗੰਧ", meaning: "smell" },
  { text: "ਘਾਟੀ", meaning: "valley" },
  { text: "ਡਬਲ", meaning: "double" },
  { text: "ਸੀਟ", meaning: "seat" },
  { text: "ਬਲਾਕ", meaning: "block" },
  { text: "ਚਾਰਟ", meaning: "chart" },
  { text: "ਟੋਪੀ", meaning: "hat" },
  { text: "ਵੇਚਣ", meaning: "sell" },
  { text: "ਘਟਾਓ", meaning: "subtract" },
  { text: "ਘਟਨਾ", meaning: "event" },
  { text: "ਖਾਸ", meaning: "particular" },
  { text: "ਸੌਦਾ", meaning: "deal" },
  { text: "ਤੈਰਾਕੀ", meaning: "swim" },
  { text: "ਜੁੱਤੀ", meaning: "shoe" },
  { text: "ਮੋਢੇ", meaning: "shoulder" },
  { text: "ਫੈਲਣ", meaning: "spread" },
  { text: "ਡੇਰੇ", meaning: "camp" },
  { text: "ਕਾਢ", meaning: "invent" },
  { text: "ਕਪਾਹ", meaning: "cotton" },
  { text: "ਜਨਮ", meaning: "born" },
  { text: "ਕਵਾਟਰ", meaning: "quart" },
  { text: "ਨੌ", meaning: "nine" },
  { text: "ਟਰੱਕ", meaning: "truck" },
  { text: "ਰੌਲਾ", meaning: "noise" },
  { text: "ਮੌਕਾ", meaning: "chance" },
  { text: "ਇਕੱਠਾ", meaning: "gather" },
  { text: "ਦੁਕਾਨ", meaning: "shop" },
  { text: "ਸੁੱਟ", meaning: "throw" },
  { text: "ਚਾਨਣ", meaning: "shine" },
  { text: "ਕਾਲਮ", meaning: "column" },
  { text: "ਅਣੂ", meaning: "molecule" },
  { text: "ਸਲੇਟੀ", meaning: "gray" },
  { text: "ਦੁਹਰਾਉ", meaning: "repeat" },
  { text: "ਵਿਆਪਕ", meaning: "broad" },
  { text: "ਲੂਣ", meaning: "salt" },
  { text: "ਨੱਕ", meaning: "nose" },
  { text: "ਬਹੁਵਚਨ", meaning: "plural" },
  { text: "ਦਾਅਵਾ", meaning: "claim" },
  { text: "ਮਹਾਦੀਪ", meaning: "continent" },
];
